"""scripts/publish-demo-bundle.py: an assembled serve bundle becomes a Pages bundle.

Every assertion here is a deploy that was refused or wrong on 2026-09-03:
a 34 MiB manifest refused by the 25 MiB cap, a symlinked bundle, a machine
path in the manifest, and a passcode gate that had no business being in the
bundle because access control is the owner's, through Cloudflare Access.
"""

from __future__ import annotations

import gzip
import importlib.util
import json
import os
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "publish-demo-bundle.py"


def _load():
    spec = importlib.util.spec_from_file_location("publish_demo_bundle", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def publish():
    return _load()


def _code_lines(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith(("*", "/*", "//")))


def _serve_bundle(tmp_path: Path, big_bytes: int) -> Path:
    """A serve bundle shaped like assemble-serve.py's output: architecture is a
    symlink to a derived directory whose shards are symlinks to a canonical one,
    plus a stale functions/ directory the way demo-site.py used to leave one."""
    canonical = tmp_path / "canonical"
    (canonical / "data").mkdir(parents=True)
    (canonical / "data" / "detail-big.json").write_text(
        json.dumps({"pad": "x" * big_bytes}), encoding="utf-8"
    )
    (canonical / "data" / "detail-small.json").write_text("{}", encoding="utf-8")
    derived = tmp_path / "derived"
    (derived / "data").mkdir(parents=True)
    (derived / "manifest.json").write_text(
        json.dumps({"name": "subject", "root_path": "/Users/someone/dev/subject", "components": []}),
        encoding="utf-8",
    )
    (derived / "publication.json").write_text(
        json.dumps({
            "publication_version": 1,
            "publisher": {"name": "SysCorpus", "contact": "https://example.invalid/issues", "url": "https://example.invalid"},
            "subject": {"name": "Subject", "repo_url": "https://github.com/example/subject", "license": "MIT",
                        "commit": "0" * 40, "snapshot_date": "2026-01-01", "affiliation": "none"},
            "purpose": "evaluation",
            "update_policy": "snapshot",
            "header": {"banner": "Unofficial map of {{subject.name}}."},
            "footer": {"always": ["Generated by {{generated_by.tool}}."]},
            "disclaimers": ["Unofficial."],
            "access": {"visibility": "private-preview", "gate": "Cloudflare Access on the hostname"},
            "generated_by": {"tool": "SysCorpus", "version": "0"},
        }),
        encoding="utf-8",
    )
    (derived / "UPSTREAM-LICENSE.txt").write_text("MIT", encoding="utf-8")
    for name in ("detail-big.json", "detail-small.json"):
        os.symlink(canonical / "data" / name, derived / "data" / name)
    serve = tmp_path / "serve"
    serve.mkdir()
    (serve / "index.html").write_text("<html></html>", encoding="utf-8")
    (serve / "functions").mkdir()
    (serve / "functions" / "_middleware.js").write_text("// stale gate", encoding="utf-8")
    os.symlink(derived, serve / "architecture")
    return serve


def test_build_produces_a_flat_bundle_under_the_cap_with_no_auth(publish, tmp_path, monkeypatch):
    # A 20 KB cap makes the padded shard the one oversized file: the other
    # files are smaller than the cap, and 200 KB of padding gzips to well
    # under it, which is the whole premise of the mechanism.
    cap = 20_000
    monkeypatch.setattr(publish, "PAGES_MAX_FILE_BYTES", cap)
    serve = _serve_bundle(tmp_path, big_bytes=200_000)
    out = tmp_path / "out"
    publish.dereference_copy(serve, out)
    assert not any(p.is_symlink() for p in out.rglob("*")), "symlinks must be resolved"
    assert not (out / "functions").exists(), "a stale functions/ gate is dropped on copy"

    assert publish.scrub_root_path(out / "architecture") == "/Users/someone/dev/subject"
    manifest = json.loads((out / "architecture" / "manifest.json").read_text())
    assert manifest["root_path"] == "" and "root_path_note" in manifest

    assert publish.hoist_notices(out) == ["UPSTREAM-LICENSE.txt"]
    assert (out / "UPSTREAM-LICENSE.txt").is_file()

    gzipped = publish.compress_oversized(out, cap=cap)
    assert gzipped == ["/architecture/data/detail-big.json"]
    assert not (out / "architecture" / "data" / "detail-big.json").exists()
    with gzip.open(out / "architecture" / "data" / "detail-big.json.gz", "rt") as fh:
        assert json.load(fh)["pad"].startswith("xxx")
    assert (out / "architecture" / "data" / "detail-small.json").is_file(), "small files stay plain"

    publish.write_worker(out, gzipped)
    worker = (out / "_worker.js").read_text()
    assert '"/architecture/data/detail-big.json"' in worker
    assert "__GZIPPED_JSON__" not in worker
    assert "import" not in _code_lines(worker), "the Worker imports nothing; it serves gzip and defers to assets"
    assert not (out / "preview-gate.js").exists()

    assert publish.safety_errors(out, cap=cap) == []


def test_any_authentication_artifact_is_a_refusal(publish, tmp_path):
    out = tmp_path / "gated"
    (out / "architecture").mkdir(parents=True)
    (out / "index.html").write_text("<html></html>", encoding="utf-8")
    (out / "UPSTREAM-LICENSE.txt").write_text("MIT", encoding="utf-8")
    (out / "architecture" / "publication.json").write_text("{}", encoding="utf-8")
    (out / "architecture" / "manifest.json").write_text("{}", encoding="utf-8")
    (out / "functions").mkdir()
    (out / "preview-gate.js").write_text("export async function onRequest() {}", encoding="utf-8")
    (out / "_worker.js").write_text(
        'import { onRequest } from "./preview-gate.js";\nconst c = env.PREVIEW_PASSCODE;\n'
        'export default { fetch: (r, env) => onRequest({ request: r, env }) };\n', encoding="utf-8"
    )
    errors = publish.safety_errors(out, cap=10**9)
    joined = "\n".join(errors)
    assert "functions is in the bundle" in joined
    assert "preview-gate.js is in the bundle" in joined
    assert "_worker.js contains 'PREVIEW_PASSCODE'" in joined
    assert "_worker.js contains 'onRequest('" in joined
    assert all("Cloudflare Access, never the bundle" in e for e in errors)


def test_safety_errors_name_every_other_refusal(publish, tmp_path):
    out = tmp_path / "bad"
    (out / "architecture").mkdir(parents=True)
    (out / "architecture" / "manifest.json").write_text(
        json.dumps({"root_path": "/Users/someone/dev/subject"}), encoding="utf-8"
    )
    (out / "architecture" / "huge.json").write_text("x" * 200, encoding="utf-8")
    (out / "architecture" / "big.json.gz").write_bytes(b"\x1f\x8b")
    os.symlink(out / "architecture" / "huge.json", out / "link.json")
    errors = publish.safety_errors(out, cap=100)
    joined = "\n".join(errors)
    assert "no index.html" in joined
    assert "no upstream license" in joined
    assert "no architecture/publication.json" in joined
    assert "root_path still names" in joined
    assert "symlink in bundle: link.json" in joined
    assert "huge.json is" in joined and "over the Pages cap" in joined
    assert "gzip assets present but no _worker.js" in joined


def test_worker_template_serves_gzip_and_carries_no_auth(publish):
    template = publish.WORKER_TEMPLATE.read_text()
    assert "__GZIPPED_JSON__" in template
    assert 'encodeBody: "manual"' in template, "without it the runtime gzips the gzip"
    code = _code_lines(template)
    for marker in publish.FORBIDDEN_AUTH_MARKERS:
        assert marker not in code, f"the Worker template must not carry {marker!r}"
    assert "import" not in code
