"""The publish gate for publication.json (PUBLICATION-METADATA.md rule 2).

For a public map of a codebase we do not own, publication.json carries the
entire legal and ethical framing: the unofficial and not-affiliated notice, the
upstream license, the exact commit. Before this gate existed the file could be
absent and nothing said so, which is the silent failure the design warned about.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "validate-publication.py"
SCHEMA = REPO_ROOT / "docs" / "publication" / "publication.schema.json"
TEMPLATES = REPO_ROOT / "docs" / "publication" / "templates"


def _load():
    spec = importlib.util.spec_from_file_location("validate_publication", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


vp = _load()


def _valid_owner_doc() -> dict:
    return {
        "publication_version": 1,
        "publisher": {"name": "Example Co", "contact": "team@example.com"},
        "subject": {
            "name": "Example",
            "commit": "abc1234",
            "snapshot_date": "2026-08-18",
            "affiliation": "owner",
        },
        "purpose": "documentation",
        "update_policy": "periodic",
        "header": {"banner": "Architecture map of Example."},
        "footer": {"always": ["Generated by SysCorpus."]},
        "disclaimers": [],
        "access": {"visibility": "public"},
        "generated_by": {"tool": "solution-explorer", "version": "1.2.0"},
    }


def _valid_showcase_doc() -> dict:
    doc = _valid_owner_doc()
    doc["subject"].update({
        "affiliation": "none",
        "license": "MIT",
        "repo_url": "https://github.com/example/example",
    })
    doc["purpose"] = "demo"
    doc["header"]["banner"] = (
        "Unofficial architecture map of {{subject.name}} at {{subject.commit}}. "
        "Not affiliated with the project."
    )
    return doc


# ---------------------------------------------------------------------------
# The contract this gate enforces
# ---------------------------------------------------------------------------

def test_a_complete_document_passes():
    assert vp.validate_doc(_valid_owner_doc()) == []
    assert vp.validate_doc(_valid_showcase_doc()) == []


@pytest.mark.parametrize("key", [
    "publication_version", "publisher", "subject", "purpose", "update_policy",
    "header", "footer", "disclaimers", "access", "generated_by",
])
def test_every_required_top_level_key_is_enforced(key):
    doc = _valid_owner_doc()
    del doc[key]
    errors = vp.validate_doc(doc)
    assert any(key in e for e in errors), f"dropping {key} must be reported; got {errors}"


@pytest.mark.parametrize("parent,child", [
    ("publisher", "name"), ("publisher", "contact"),
    ("subject", "commit"), ("subject", "snapshot_date"), ("subject", "affiliation"),
    ("header", "banner"), ("footer", "always"), ("access", "visibility"),
])
def test_every_required_nested_key_is_enforced(parent, child):
    doc = _valid_owner_doc()
    del doc[parent][child]
    errors = vp.validate_doc(doc)
    assert any(f"{parent}.{child}" in e for e in errors), f"got {errors}"


def test_provenance_must_be_real():
    # A snapshot with no usable commit is a publication nobody can reproduce.
    doc = _valid_owner_doc()
    doc["subject"]["commit"] = "main"
    assert any("git SHA" in e for e in vp.validate_doc(doc))
    doc = _valid_owner_doc()
    doc["subject"]["snapshot_date"] = "last Tuesday"
    assert any("ISO date" in e for e in vp.validate_doc(doc))


def test_unknown_enum_values_are_rejected():
    doc = _valid_owner_doc()
    doc["access"]["visibility"] = "sort-of-public"
    assert any("access.visibility" in e for e in vp.validate_doc(doc))


# ---------------------------------------------------------------------------
# Obligations that only apply when the subject is not ours
# ---------------------------------------------------------------------------

def test_publishing_someone_elses_code_requires_saying_so():
    doc = _valid_showcase_doc()
    doc["header"]["banner"] = "Architecture map of Example."  # the honest framing removed
    errors = vp.validate_doc(doc)
    assert any("unofficial" in e for e in errors), f"got {errors}"


def test_the_unofficial_notice_may_live_in_the_footer_or_disclaimers():
    # The obligation is that a reader sees it, not that it sits in one field.
    for region in ("footer", "disclaimers"):
        doc = _valid_showcase_doc()
        doc["header"]["banner"] = "Architecture map of Example."
        if region == "footer":
            doc["footer"]["always"].append("Unofficial, not affiliated with the project.")
        else:
            doc["disclaimers"] = ["This is an unofficial map."]
        assert vp.validate_doc(doc) == [], f"{region} should satisfy the obligation"


def test_publishing_someone_elses_code_requires_their_license_and_repo():
    # The viewer renders upstream README and doc excerpts, so a demo
    # redistributes third-party text and the notice has to travel with it.
    doc = _valid_showcase_doc()
    del doc["subject"]["license"]
    assert any("subject.license" in e for e in vp.validate_doc(doc))
    doc = _valid_showcase_doc()
    del doc["subject"]["repo_url"]
    assert any("subject.repo_url" in e for e in vp.validate_doc(doc))


def test_our_own_projects_are_not_burdened_with_the_unofficial_obligations():
    doc = _valid_owner_doc()  # affiliation owner, no license or repo_url
    assert vp.validate_doc(doc) == []


def test_a_substitution_that_resolves_to_nothing_is_caught():
    doc = _valid_owner_doc()
    doc["header"]["banner"] = "Map of {{subject.nickname}}"
    assert any("resolves to nothing" in e for e in vp.validate_doc(doc))


# ---------------------------------------------------------------------------
# Shipping an unfilled template is the failure this exists to prevent
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("template", sorted(TEMPLATES.glob("publication.*.json")))
def test_the_shipped_templates_are_rejected_as_unfilled(template):
    doc = json.loads(template.read_text(encoding="utf-8"))
    errors = vp.validate_doc(doc)
    assert errors, f"{template.name} must not validate while it still has EDIT markers"
    assert "unfilled template" in errors[0]
    # One clear cause, not a wall of downstream symptoms.
    assert len(errors) == 1


def test_a_filled_template_validates():
    # Proves the templates are usable, not merely rejectable: fill every EDIT
    # marker in the showcase boilerplate and it passes.
    doc = json.loads((TEMPLATES / "publication.showcase.json").read_text(encoding="utf-8"))
    fills = {
        "publisher.name": "Example Co", "publisher.contact": "team@example.com",
        "publisher.url": "https://example.com",
        "subject.name": "Example", "subject.commit": "abc1234def",
        "subject.homepage_url": "https://example.com/product",
        "subject.license": "MIT", "subject.repo_url": "https://github.com/example/example",
        "generated_by.version": "1.2.0",
    }
    for path, value in fills.items():
        parent, key = path.split(".")
        if parent in doc and key in doc[parent]:
            doc[parent][key] = value
    doc["subject"].setdefault("snapshot_date", "2026-08-18")
    if str(doc["subject"].get("snapshot_date", "")).upper().startswith("EDIT"):
        doc["subject"]["snapshot_date"] = "2026-08-18"
    leftover = vp._unfilled_placeholders(doc)
    assert not leftover, f"test did not fill everything: {leftover}"
    assert vp.validate_doc(doc) == []


# ---------------------------------------------------------------------------
# The gate's two modes, and the drift guard
# ---------------------------------------------------------------------------

def test_missing_file_warns_by_default_and_fails_under_require(tmp_path, capsys):
    assert vp.main([str(tmp_path)]) == 0
    warned = capsys.readouterr().err
    assert "WARNING" in warned and "no publisher" in warned
    assert vp.main([str(tmp_path), "--require"]) == 2


def test_an_invalid_file_fails_in_both_modes(tmp_path):
    target = tmp_path / "publication.json"
    doc = _valid_owner_doc()
    del doc["access"]
    target.write_text(json.dumps(doc), encoding="utf-8")
    assert vp.main([str(tmp_path)]) == 1, "invalid is never tolerated, flag or not"
    assert vp.main([str(tmp_path), "--require"]) == 1


def test_a_valid_file_passes_and_reports_its_provenance(tmp_path, capsys):
    target = tmp_path / "publication.json"
    target.write_text(json.dumps(_valid_showcase_doc()), encoding="utf-8")
    # A showcase publication also has to ship the upstream license text.
    (tmp_path / "UPSTREAM-LICENSE.txt").write_text("MIT License ...", encoding="utf-8")
    assert vp.main([str(tmp_path), "--require"]) == 0
    out = capsys.readouterr().out
    assert "publication.json OK" in out and "affiliation=none" in out


def test_unparseable_json_fails_with_the_boilerplate_hint(tmp_path, capsys):
    (tmp_path / "publication.json").write_text("{not json", encoding="utf-8")
    assert vp.main([str(tmp_path)]) == 1
    assert "templates" in capsys.readouterr().err


def test_the_hardcoded_contract_matches_the_schema_file():
    """The validator is stdlib-only so it runs where action.yml runs, which
    means the contract is written twice. This is the guard against drift."""
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    assert sorted(vp.REQUIRED_TOP) == sorted(schema["required"])
    for parent, children in vp.REQUIRED_NESTED.items():
        assert sorted(children) == sorted(schema["properties"][parent]["required"]), parent
    for path, allowed in vp.ENUMS.items():
        node = schema["properties"]
        for i, key in enumerate(path):
            node = node[key] if i == 0 else node["properties"][key]
        assert sorted(allowed) == sorted(node["enum"]), path


# ---------------------------------------------------------------------------
# The upstream license must ship with what we publish
# ---------------------------------------------------------------------------

def test_publishing_someone_elses_code_requires_their_license_text_in_the_bundle(tmp_path):
    # subject.license names the identifier; this is about the TEXT. The viewer
    # renders upstream README and doc excerpts, so the bundle redistributes
    # third-party text and the notice has to travel with it.
    (tmp_path / "publication.json").write_text(json.dumps(_valid_showcase_doc()), encoding="utf-8")
    assert vp.main([str(tmp_path), "--require"]) == 1
    (tmp_path / "UPSTREAM-LICENSE.txt").write_text("MIT License ...", encoding="utf-8")
    assert vp.main([str(tmp_path), "--require"]) == 0


def test_our_own_projects_need_no_upstream_license_file(tmp_path):
    (tmp_path / "publication.json").write_text(json.dumps(_valid_owner_doc()), encoding="utf-8")
    assert vp.main([str(tmp_path), "--require"]) == 0


def test_the_bundle_check_only_runs_where_a_bundle_is_being_published(tmp_path):
    # Without --require there is no publish happening, so a missing upstream
    # license is not an error; the document itself is still validated.
    (tmp_path / "publication.json").write_text(json.dumps(_valid_showcase_doc()), encoding="utf-8")
    assert vp.main([str(tmp_path)]) == 0
