import { describe, it, expect } from "vitest";
import {
  parsePublication,
  resolvePublicationText,
  publicationDisplayName,
} from "../utils/publication";
import type { Publication } from "../types";

// A minimal valid publication.json, mirroring docs/publication/publication.schema.json.
function validRaw(): Record<string, unknown> {
  return {
    publication_version: 1,
    publisher: { name: "Acme Docs", contact: "docs@acme.example", url: "" },
    subject: {
      name: "Demo Publication Subject",
      repo_url: "https://example.com/repo",
      license: "MIT",
      commit: "abc1234",
      snapshot_date: "2026-07-21",
      affiliation: "owner",
    },
    purpose: "documentation",
    update_policy: "continuous",
    header: { banner: "Map of {{subject.name}} at {{subject.commit}}.", front_page: [] },
    footer: {
      always: ["Generated by {{generated_by.tool}} {{generated_by.version}}."],
    },
    context: [],
    disclaimers: [],
    access: { visibility: "public", gate: null },
    generated_by: { tool: "solution-explorer", version: "0.0.0-test" },
  };
}

describe("parsePublication validation", () => {
  it("accepts a valid sidecar and returns a typed Publication", () => {
    const pub = parsePublication(validRaw());
    expect(pub).not.toBeNull();
    expect(pub?.subject.name).toBe("Demo Publication Subject");
    expect(pub?.access.visibility).toBe("public");
  });

  it("returns null for a non-object", () => {
    expect(parsePublication(null)).toBeNull();
    expect(parsePublication("nope")).toBeNull();
    expect(parsePublication(42)).toBeNull();
    expect(parsePublication([])).toBeNull();
  });

  it("returns null for the wrong publication_version", () => {
    const raw = validRaw();
    raw.publication_version = 2;
    expect(parsePublication(raw)).toBeNull();
  });

  it("returns null when subject.name is missing or empty", () => {
    const raw = validRaw();
    (raw.subject as Record<string, unknown>).name = "";
    expect(parsePublication(raw)).toBeNull();
    delete (raw.subject as Record<string, unknown>).name;
    expect(parsePublication(raw)).toBeNull();
  });

  it("returns null for a too-short commit or a malformed snapshot_date", () => {
    const shortCommit = validRaw();
    (shortCommit.subject as Record<string, unknown>).commit = "abc";
    expect(parsePublication(shortCommit)).toBeNull();

    const badDate = validRaw();
    (badDate.subject as Record<string, unknown>).snapshot_date = "07/21/2026";
    expect(parsePublication(badDate)).toBeNull();
  });

  it("returns null for out-of-enum affiliation/purpose/visibility", () => {
    const badAff = validRaw();
    (badAff.subject as Record<string, unknown>).affiliation = "partner";
    expect(parsePublication(badAff)).toBeNull();

    const badPurpose = validRaw();
    badPurpose.purpose = "marketing";
    expect(parsePublication(badPurpose)).toBeNull();

    const badVis = validRaw();
    (badVis.access as Record<string, unknown>).visibility = "secret";
    expect(parsePublication(badVis)).toBeNull();
  });

  it("returns null when header.banner is missing or footer.always is empty", () => {
    const noBanner = validRaw();
    (noBanner.header as Record<string, unknown>).banner = "";
    expect(parsePublication(noBanner)).toBeNull();

    const emptyFooter = validRaw();
    (emptyFooter.footer as Record<string, unknown>).always = [];
    expect(parsePublication(emptyFooter)).toBeNull();
  });
});

describe("resolvePublicationText substitution", () => {
  const pub = parsePublication(validRaw()) as Publication;

  it("substitutes dotted paths against the file itself", () => {
    expect(resolvePublicationText(pub.header.banner, pub)).toBe(
      "Map of Demo Publication Subject at abc1234.",
    );
    expect(resolvePublicationText(pub.footer.always[0], pub)).toBe(
      "Generated by solution-explorer 0.0.0-test.",
    );
  });

  it("renders an unresolved path loudly as [missing: path], never a blank", () => {
    expect(resolvePublicationText("x {{subject.nope}} y", pub)).toBe("x [missing: subject.nope] y");
    expect(resolvePublicationText("{{publisher.url}}", pub)).toBe("[missing: publisher.url]");
  });

  it("tolerates whitespace inside the braces", () => {
    expect(resolvePublicationText("{{  subject.name  }}", pub)).toBe("Demo Publication Subject");
  });
});

describe("publicationDisplayName", () => {
  const pub = parsePublication(validRaw()) as Publication;

  it("prefers subject.name when a valid publication is present", () => {
    expect(publicationDisplayName(pub, "folder-derived-name")).toBe("Demo Publication Subject");
  });

  it("falls back to the folder-derived name when publication is null", () => {
    expect(publicationDisplayName(null, "folder-derived-name")).toBe("folder-derived-name");
  });
});
