import type { Annotation, Architecture, Component } from "../types";
import { TYPE_META } from "./layout";

// Sort order for annotation target types within a component group
const TARGET_ORDER: Record<string, number> = {
  "component": 0,
  "component-name": 1,
  "component-type": 2,
  "component-framework": 3,
  "component-port": 4,
  "component-purpose": 5,
  "component-pattern": 6,
  "file": 7,
  "symbol": 8,
};

function sortAnnotations(annotations: Annotation[]): Annotation[] {
  return [...annotations].sort(
    (a, b) => (TARGET_ORDER[a.targetType] ?? 99) - (TARGET_ORDER[b.targetType] ?? 99),
  );
}

interface ComponentGroup {
  componentId: string;
  component: Component;
  annotations: Annotation[];
}

function groupByComponent(
  annotations: Annotation[],
  getComponentById: (id: string) => Component | null,
): ComponentGroup[] {
  const map = new Map<string, Annotation[]>();
  for (const a of annotations) {
    const arr = map.get(a.componentId) || [];
    arr.push(a);
    map.set(a.componentId, arr);
  }
  const groups: ComponentGroup[] = [];
  for (const [componentId, anns] of map) {
    const comp = getComponentById(componentId);
    if (!comp) continue;
    groups.push({ componentId, component: comp, annotations: sortAnnotations(anns) });
  }
  return groups;
}

/**
 * Generate the full review prompt, grouped by component.
 */
export function generateReviewPrompt(
  annotations: Annotation[],
  architecture: Architecture,
  getComponentById: (id: string) => Component | null,
): string {
  if (annotations.length === 0) return "";

  const lines: string[] = [];

  lines.push(`# Architecture Review: ${architecture.name}`);
  lines.push("");
  lines.push("The following review comments are grouped by component.");
  lines.push("Each section contains all feedback for that component, including naming,");
  lines.push("type classification, framework, purpose, patterns, files, and symbols.");
  lines.push("Please analyze this feedback and suggest concrete implementation changes.");
  lines.push("");
  lines.push("---");

  const groups = groupByComponent(annotations, getComponentById);
  let componentCounter = 0;

  for (const group of groups) {
    componentCounter++;
    appendComponentSection(lines, group, componentCounter, architecture, getComponentById);
  }

  // Summary
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("**Review Summary:**");
  lines.push(`- Total annotations: ${annotations.length}`);
  lines.push(`- Components reviewed: ${groups.length}`);

  const typeCounts: Record<string, number> = {};
  for (const a of annotations) {
    const key = a.targetType.startsWith("component-") ? "component properties" : a.targetType;
    typeCounts[key] = (typeCounts[key] || 0) + 1;
  }
  for (const [type, count] of Object.entries(typeCounts)) {
    lines.push(`  - ${type}: ${count}`);
  }

  lines.push(`- Architecture generated: ${architecture.generated_at}`);
  lines.push("");
  lines.push("Generated by solution-explorer architecture viewer.");

  return lines.join("\n");
}

/**
 * Generate a prompt for a single component's annotations.
 * Used by the per-component copy button.
 */
export function generateComponentPrompt(
  component: Component,
  annotations: Annotation[],
  architecture: Architecture,
  getComponentById: (id: string) => Component | null,
): string {
  if (annotations.length === 0) return "";

  const lines: string[] = [];

  lines.push(`# Review Feedback: ${component.name}`);
  lines.push("");
  lines.push("The following review comments are for a single component.");
  lines.push("Please analyze this feedback and suggest concrete implementation changes.");
  lines.push("");
  lines.push("---");

  const group: ComponentGroup = {
    componentId: component.id,
    component,
    annotations: sortAnnotations(annotations),
  };
  appendComponentSection(lines, group, 1, architecture, getComponentById);

  lines.push("");
  lines.push("Generated by solution-explorer architecture viewer.");

  return lines.join("\n");
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function appendComponentSection(
  lines: string[],
  group: ComponentGroup,
  componentNumber: number,
  architecture: Architecture,
  getComponentById: (id: string) => Component | null,
) {
  const comp = group.component;
  const typeLabel = TYPE_META[comp.type]?.label || comp.type;

  lines.push("");
  lines.push(`## ${componentNumber}. ${comp.name} (${typeLabel})`);
  lines.push("");
  lines.push(`- Path: \`${comp.path}\``);

  const details: string[] = [];
  if (comp.framework) details.push(`Framework: ${comp.framework}`);
  if (comp.language) details.push(`Language: ${comp.language}`);
  if (comp.port) details.push(`Port: ${comp.port}`);
  if (details.length > 0) lines.push(`- ${details.join(" | ")}`);

  if (comp.docs?.purpose) {
    lines.push(`- Purpose: ${comp.docs.purpose}`);
  }

  let subCounter = 0;
  for (const annotation of group.annotations) {
    subCounter++;
    lines.push("");
    appendAnnotationWithContext(
      lines,
      annotation,
      `${componentNumber}.${subCounter}`,
      comp,
      architecture,
      getComponentById,
    );
  }

  lines.push("");
  lines.push("---");
}

function appendAnnotationWithContext(
  lines: string[],
  annotation: Annotation,
  label: string,
  comp: Component,
  architecture: Architecture,
  getComponentById: (id: string) => Component | null,
) {
  const ctx = annotation.targetContext;

  switch (annotation.targetType) {
    case "component":
      lines.push(`### ${label}. General Component Feedback`);
      lines.push("");
      appendFeedback(lines, annotation.text);
      lines.push("");
      appendComponentContext(lines, comp, architecture, getComponentById);
      break;

    case "component-name":
      lines.push(`### ${label}. Component Name`);
      lines.push(`- Current name: \`${comp.name}\``);
      lines.push(`- Component path: \`${comp.path}\``);
      if (ctx?.nameSource) {
        lines.push(`- Name derived from: ${ctx.nameSource}`);
      }
      if (ctx?.configFiles && ctx.configFiles.length > 0) {
        lines.push(`- Config files that may define the name:`);
        ctx.configFiles.forEach((cf) => lines.push(`  - \`${cf}\``));
      }
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;

    case "component-type":
      lines.push(`### ${label}. Type Classification`);
      lines.push(`- Current type: \`${comp.type}\` (displayed as "${TYPE_META[comp.type]?.label || comp.type}")`);
      lines.push(`- Component path: \`${comp.path}\``);
      lines.push(`- Type is assigned by the analyzer based on framework detection, server indicators, and project structure`);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;

    case "component-framework":
      lines.push(`### ${label}. Framework`);
      lines.push(`- Current framework: ${comp.framework || "(none)"}`);
      lines.push(`- Component path: \`${comp.path}\``);
      lines.push(`- Framework is detected from dependencies (package.json, Podfile, etc.) and import patterns`);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;

    case "component-port":
      lines.push(`### ${label}. Port`);
      lines.push(`- Current port: ${comp.port || "(none)"}`);
      lines.push(`- Component path: \`${comp.path}\``);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;

    case "component-purpose":
      lines.push(`### ${label}. Purpose / Description`);
      lines.push(`- Current purpose: ${comp.docs?.purpose || "(none)"}`);
      lines.push(`- Component path: \`${comp.path}\``);
      lines.push(`- Purpose is extracted from: README.md first paragraph, CLAUDE.md, or code analysis`);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;

    case "component-pattern": {
      const pattern = ctx?.patternValue || annotation.targetName;
      lines.push(`### ${label}. Pattern: ${pattern}`);
      lines.push(`- Pattern in question: ${pattern}`);
      if (comp.docs?.patterns && comp.docs.patterns.length > 0) {
        lines.push(`- All detected patterns: ${comp.docs.patterns.join(", ")}`);
      }
      lines.push(`- Component path: \`${comp.path}\``);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;
    }

    case "file": {
      const fileInfo = architecture.files.find((f) => f.path === annotation.targetId);
      lines.push(`### ${label}. File: ${annotation.targetName}`);
      if (fileInfo) {
        lines.push(`- Path: \`${fileInfo.path}\``);
        lines.push(`- Language: ${fileInfo.language}`);
        lines.push(`- Lines: ${fileInfo.lines}`);
        if (fileInfo.symbols.length > 0) {
          const symbolNames = fileInfo.symbols
            .map((sid) => architecture.symbols.find((s) => s.id === sid)?.name)
            .filter(Boolean);
          if (symbolNames.length > 0) {
            lines.push(`- Symbols: ${symbolNames.slice(0, 15).join(", ")}${symbolNames.length > 15 ? ` ... +${symbolNames.length - 15} more` : ""}`);
          }
        }
      } else {
        lines.push(`- Path: ${annotation.targetId}`);
      }
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;
    }

    case "symbol": {
      const symbol = architecture.symbols.find((s) => s.id === annotation.targetId);
      lines.push(`### ${label}. Symbol: ${annotation.targetName}`);
      if (symbol) {
        lines.push(`- Kind: ${symbol.kind}`);
        lines.push(`- File: \`${symbol.file}:${symbol.line}\``);
        lines.push(`- Visibility: ${symbol.visibility}`);
        if (symbol.docstring) {
          lines.push(`- Docstring: ${symbol.docstring.slice(0, 200)}${symbol.docstring.length > 200 ? "..." : ""}`);
        }
        if (symbol.code_preview) {
          lines.push("");
          lines.push("```");
          lines.push(symbol.code_preview);
          lines.push("```");
        }
      }
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;
    }

    default:
      lines.push(`### ${label}. ${annotation.targetType}: ${annotation.targetName}`);
      lines.push("");
      appendFeedback(lines, annotation.text);
      break;
  }
}

function appendFeedback(lines: string[], text: string) {
  lines.push("**Feedback:**");
  text.split("\n").forEach((line) => {
    lines.push(`> ${line}`);
  });
}

function appendComponentContext(
  lines: string[],
  comp: Component,
  architecture: Architecture,
  getComponentById: (id: string) => Component | null,
) {
  lines.push("**Component Context:**");
  lines.push(`- Path: \`${comp.path}\``);

  if (comp.docs?.purpose) {
    lines.push(`- Purpose: ${comp.docs.purpose}`);
  }

  const details: string[] = [];
  if (comp.framework) details.push(`Framework: ${comp.framework}`);
  if (comp.language) details.push(`Language: ${comp.language}`);
  if (details.length > 0) lines.push(`- ${details.join(" | ")}`);

  if (comp.metrics) {
    const metrics: string[] = [];
    if (comp.metrics.files > 0) metrics.push(`${comp.metrics.files} files`);
    if (comp.metrics.lines > 0) metrics.push(`${comp.metrics.lines} lines`);
    if (metrics.length > 0) lines.push(`- Size: ${metrics.join(", ")}`);
  }

  if (comp.docs?.patterns && comp.docs.patterns.length > 0) {
    lines.push(`- Patterns: ${comp.docs.patterns.join(", ")}`);
  }

  if (comp.docs?.tech_stack && comp.docs.tech_stack.length > 0) {
    lines.push(`- Tech Stack: ${comp.docs.tech_stack.join(", ")}`);
  }

  if (comp.docs?.api_endpoints && comp.docs.api_endpoints.length > 0) {
    lines.push(`- API Endpoints:`);
    comp.docs.api_endpoints.slice(0, 10).forEach((ep) => {
      lines.push(`  - ${ep.method} ${ep.path}`);
    });
    if (comp.docs.api_endpoints.length > 10) {
      lines.push(`  - ... and ${comp.docs.api_endpoints.length - 10} more`);
    }
  }

  if (comp.docs?.env_vars && comp.docs.env_vars.length > 0) {
    lines.push(`- Environment Variables: ${comp.docs.env_vars.join(", ")}`);
  }

  if (comp.port) {
    lines.push(`- Port: ${comp.port}`);
  }

  const rels = architecture.relationships.filter(
    (r) => r.source === comp.id || r.target === comp.id,
  );
  if (rels.length > 0) {
    lines.push("");
    lines.push("**Relationships:**");
    rels.slice(0, 10).forEach((r) => {
      const isSource = r.source === comp.id;
      const otherId = isSource ? r.target : r.source;
      const otherComp = getComponentById(otherId);
      const otherName = otherComp?.name || otherId;
      const direction = isSource ? "->" : "<-";
      lines.push(`- ${direction} ${otherName} (${r.type}${r.label ? `: ${r.label}` : ""})`);
    });
    if (rels.length > 10) {
      lines.push(`- ... and ${rels.length - 10} more relationships`);
    }
  }

  if (comp.entry_points && comp.entry_points.length > 0) {
    lines.push("");
    lines.push("**Entry Points:**");
    comp.entry_points.slice(0, 5).forEach((ep) => {
      lines.push(`- ${ep}`);
    });
  }
}
