#!/usr/bin/env python3
"""SysCorpus demo-program harness (DEMO-PROGRAM.md section 4).

Orchestration over CLIs that already exist (`analyze.py`, `analyze.py enhance`,
`scripts/projection-diff.py`, `scripts/validate-publication.py`, `wrangler`).
There is no new analysis capability here, only the local execution path,
cadence bookkeeping, and the gate that decides whether a demo may go public.

Registry (`demos/registry/<slug>.json`) mirrors `tests/golden/<name>/corpus.lock`
on purpose: one committed file per outside codebase we care about (section 4.1).
The difference from a golden corpus is policy, not mechanics: a golden corpus is
FROZEN at a pinned commit so any diff is attributable to OUR engine; a demo
TRACKS upstream (`policy.follow`) so it is never stale, and the harness records
the exact resolved SHA it analyzed on every refresh.

`policy.history` (`full` | `shallow`) is an ADDITION to the 4.1 schema, not in
the original design doc. It exists because a depth-1 clone was measured to
produce a degenerate git-activity signal (DECISIONS-N3.md): every file gets
`commit_count: 1`, one author, and `cochange_pair` comes out empty, so the
Activity lens is not merely empty (honest) but populated and WRONG (a plausible
lie). `full` is the decided default: no `--depth` on the fetch, and an existing
shallow clone is repaired in place with `git fetch --unshallow` rather than left
shallow.

Layout:
    demos/registry/<slug>.json   the pinned-policy registry entry (committed)
    demos/runs/<slug>/<date>/    run records: report.json/.md, validate.json,
                                  diff.json, findings.json (committed, small,
                                  reviewable -- section 4/8 call this out
                                  explicitly: "run records committed")
    demos/hub/                   the generated static hub site (committed,
                                  regenerated by `hub`, same idiom as the
                                  repo-root architecture.json: regenerable but
                                  tracked, because it IS the reviewed artifact)
    ~/dev/.demo-corpus/<slug>/         the fetched clone (gitignored by being
                                  outside the repo entirely; override with the
                                  DEMO_CORPUS_DIR env var)
    ~/dev/.demo-corpus/_out/<slug>/    analysis output: the split projection
                                  (architecture/manifest.json + shards), the
                                  persistent fact store (index.db, warm across
                                  refreshes), the enrichment report, and a
                                  dated history/ of past manifests for `diff`.
                                  A SIBLING of the fetched source, mirroring
                                  golden-corpus.py's `_out_dir`: analyze.py's
                                  companion artifacts must never land inside the
                                  scanned corpus or the next scan counts the
                                  harness's own output as source.

Subcommands (mirroring golden-corpus.py's shape, DEMO-PROGRAM.md 4.2):
    list                 registry contents
    status               last successful run per demo, and what is due
    fetch <slug>         clone/fetch into the corpus cache, resolve the ref,
                         record the exact SHA
    analyze <slug>       v2 split projection into a persistent per-demo store
    enhance <slug>       analyze.py enhance --update, cost-ceilinged
    validate <slug>      the 3.6 checklist + the section 2 graduation gate.
                         THE ONE HARD REQUIREMENT: a gate whose instrument does
                         not exist (there are two: the classification accuracy
                         audit, 5.3, and the human-recorded license review,
                         6.1) reports NOT_IMPLEMENTED and fails the run in the
                         default strict mode. It is never silently skipped,
                         passed, or omitted. --allow-unimplemented downgrades
                         NOT_IMPLEMENTED to a warning; it never touches FAIL.
    diff <slug>          projection diff against the previous run (no previous
                         run is not an error: "no baseline", exit 0)
    deploy <slug>        wrangler pages deploy. Outward-facing, so it is a
                         DRY RUN by construction unless the DEMO_DEPLOY_ALLOW
                         env var is set (or --dry-run is passed, which always
                         wins). Nothing public happens by accident.
    report <slug>        run record, JSON and markdown, under demos/runs/
    findings <slug>      the cheap deterministic machine gates from 5.1,
                         written to findings.json with the stable fingerprint
                         from 5.2 (`demo-finding:<slug>:<check>:<hash>`).
                         Does NOT file GitHub issues. Turning a finding into an
                         issue (dedup, labels, auto-close) is a separate,
                         not-yet-built task (5.2); this only computes and
                         records the findings themselves.
    refresh <slug>       fetch -> analyze -> enhance -> validate -> diff ->
                         report -> findings, stopping at the first failure.
                         Deliberately does NOT deploy: DISCLOSURE-POLICY.md
                         requires a private preview and review before any
                         public deploy, so deploy stays a separate, deliberate
                         step even after every gate is green.
    refresh --due        every demo whose cadence is up
    hub                  regenerate demos/hub/index.html from the registry and
                         the run records: self-contained, no build step

Where this spec was silent, the choice made and why is in each function's
docstring rather than left implicit.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import importlib.util
import json
import os
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
REGISTRY_DIR = REPO_ROOT / "demos" / "registry"
RUNS_DIR = REPO_ROOT / "demos" / "runs"
HUB_DIR = REPO_ROOT / "demos" / "hub"
ANALYZE_SCRIPT = REPO_ROOT / "analyze.py"

DEMO_CORPUS_DIR_ENV = "DEMO_CORPUS_DIR"
DEMO_DEPLOY_ALLOW_ENV = "DEMO_DEPLOY_ALLOW"


def _default_corpus_dir() -> Path:
    override = os.environ.get(DEMO_CORPUS_DIR_ENV)
    if override:
        return Path(override).expanduser()
    return Path.home() / "dev" / ".demo-corpus"


# A module global, overridable per-call via the corpus_dir parameter that every
# path-deriving function below accepts, and swappable wholesale in tests (see
# tests/test_demo_site.py's fixture) -- the same pattern golden-corpus.py uses
# for GOLDEN_DIR/CACHE_DIR.
CORPUS_DIR = _default_corpus_dir()

# Markers bounding the harness-managed excludes block appended to a fetched
# corpus's .gitignore, exactly the golden-corpus.py idiom (copied, not
# reinvented): idempotent, rewritten in full on every fetch.
_EXCLUDE_BEGIN = "# >>> demo-site excludes (managed)"
_EXCLUDE_END = "# <<< demo-site excludes (managed)"


def _load_projection_diff():
    path = SCRIPTS_DIR / "projection-diff.py"
    spec = importlib.util.spec_from_file_location("projection_diff", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_validate_publication():
    path = SCRIPTS_DIR / "validate-publication.py"
    spec = importlib.util.spec_from_file_location("validate_publication", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def _rmtree(path: Path) -> None:
    shutil.rmtree(path, ignore_errors=True)


# ---------------------------------------------------------------------------
# Registry (demos/registry/<slug>.json)
# ---------------------------------------------------------------------------

REQUIRED_TOP = ["slug", "subject", "track", "policy", "hosting", "cadence", "budget", "gates", "consent"]
REQUIRED_NESTED = {
    "subject": ["name", "repo", "license", "governance"],
    # "history" is deliberately not required here: it defaults to "full" (the
    # decided default) when absent, so an entry written before this field
    # existed still validates. Its VALUE, once present or defaulted, is still
    # checked below against HISTORY_VALUES.
    "policy": ["follow", "pin", "exclude"],
    "hosting": ["cf_project", "url"],
    "budget": ["max_cost_usd", "max_wall_minutes"],
    "gates": ["coverage", "max_detect_only_line_share", "min_enrichment_score"],
    "consent": ["required", "state", "contacted"],
}
FOLLOW_VALUES = {"default-branch", "latest-tag", "pinned"}
HISTORY_VALUES = {"full", "shallow"}

# Cadence granularities the harness understands. Only "weekly" appears in
# DEMO-PROGRAM.md; daily/monthly are added for a program that outlives Wave 1,
# and an unrecognized value is a hard error rather than a silent default, same
# spirit as the rest of this file's "never silently pass" rule.
CADENCE_SECONDS = {"daily": 86_400, "weekly": 7 * 86_400, "monthly": 30 * 86_400}


def validate_registry(doc) -> list[str]:
    """Structural errors in a registry entry, most specific first. Empty is valid.

    Deliberately loose on `track`: DEMO-PROGRAM.md section 2 names "Track A,
    published" and "Track B, capability-forcing targets" but the only literal
    value the design gives (4.1's worked example) is "published". Rather than
    guess Track B's exact string and reject a legitimate value, `track` is only
    required to be a non-empty string.
    """
    errors: list[str] = []
    if not isinstance(doc, dict):
        return ["registry entry must be a JSON object"]

    for key in REQUIRED_TOP:
        if key not in doc:
            errors.append(f"missing required key: {key}")
    for parent, children in REQUIRED_NESTED.items():
        node = doc.get(parent)
        if node is None:
            continue  # already reported by the top-level pass
        if not isinstance(node, dict):
            errors.append(f"{parent} must be an object")
            continue
        for child in children:
            if child not in node:
                errors.append(f"missing required key: {parent}.{child}")

    if not doc.get("slug"):
        errors.append("slug must be a non-empty string")
    if doc.get("track") is not None and not str(doc.get("track")):
        errors.append("track must be a non-empty string")

    policy = doc.get("policy") or {}
    follow = policy.get("follow")
    if follow is not None and follow not in FOLLOW_VALUES:
        errors.append(f"policy.follow must be one of {sorted(FOLLOW_VALUES)}, got {follow!r}")
    if follow == "pinned" and not policy.get("pin"):
        errors.append("policy.follow is 'pinned' but policy.pin is not set")
    history = policy.get("history", "full")
    if history not in HISTORY_VALUES:
        errors.append(f"policy.history must be one of {sorted(HISTORY_VALUES)}, got {history!r}")

    cadence = doc.get("cadence")
    if cadence is not None and cadence not in CADENCE_SECONDS:
        errors.append(f"cadence must be one of {sorted(CADENCE_SECONDS)}, got {cadence!r}")

    errors.extend(_enrichment_errors(doc.get("enrichment")))

    return errors


# The enrichment block is OPTIONAL: an entry without one runs the classic single
# bulk pass, which is what every entry did before the ladder existed. When it is
# present it is validated strictly, because a typo in a model binding or an
# iteration bound would otherwise be discovered by a run that had already spent
# most of its budget.
ENRICHMENT_PIPELINES = frozenset({"bulk", "ladder"})


def _enrichment_errors(block) -> list[str]:
    if block is None:
        return []
    if not isinstance(block, dict):
        return ["enrichment must be an object"]
    errors: list[str] = []
    pipeline = block.get("pipeline", "bulk")
    if pipeline not in ENRICHMENT_PIPELINES:
        errors.append(
            f"enrichment.pipeline must be one of {sorted(ENRICHMENT_PIPELINES)}, "
            f"got {pipeline!r}"
        )
    models = block.get("models")
    if models is not None and not isinstance(models, dict):
        errors.append("enrichment.models must be an object of rung -> binding")
    iteration = block.get("iteration")
    if iteration is not None:
        if not isinstance(iteration, dict):
            errors.append("enrichment.iteration must be an object")
        else:
            for key in ("min_rounds", "max_rounds"):
                value = iteration.get(key)
                if value is not None and (not isinstance(value, int) or value < 0):
                    errors.append(
                        f"enrichment.iteration.{key} must be a non-negative integer, "
                        f"got {value!r}"
                    )
            lo, hi = iteration.get("min_rounds"), iteration.get("max_rounds")
            if isinstance(lo, int) and isinstance(hi, int) and lo > hi:
                errors.append(
                    f"enrichment.iteration.min_rounds ({lo}) exceeds max_rounds "
                    f"({hi}), so the forced floor could never be reached"
                )
    return errors


def load_registry(slug: str, registry_dir: Optional[Path] = None) -> dict:
    """Load and validate one registry entry. `policy.history` defaults to 'full'
    (the decided default) when absent, so an older entry written before this
    field existed still loads."""
    registry_dir = registry_dir or REGISTRY_DIR
    path = registry_dir / f"{slug}.json"
    if not path.exists():
        raise FileNotFoundError(f"no registry entry for '{slug}' at {path}")
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"registry entry {path} is not valid JSON: {exc}") from exc

    errors = validate_registry(doc)
    if doc.get("slug") and doc["slug"] != slug:
        errors.append(f"slug {doc['slug']!r} does not match filename '{slug}.json'")
    if errors:
        raise ValueError(f"registry entry {path} is invalid: " + "; ".join(errors))

    doc.setdefault("policy", {}).setdefault("history", "full")
    return doc


def list_registry(registry_dir: Optional[Path] = None) -> list[str]:
    """Slugs of every registered demo (a `<slug>.json` file), sorted."""
    registry_dir = registry_dir or REGISTRY_DIR
    if not registry_dir.exists():
        return []
    return sorted(p.stem for p in registry_dir.glob("*.json"))


def iter_registry(registry_dir: Optional[Path] = None) -> list[dict]:
    return [load_registry(slug, registry_dir) for slug in list_registry(registry_dir)]


def cadence_period_seconds(cadence: str) -> int:
    try:
        return CADENCE_SECONDS[cadence]
    except KeyError:
        raise ValueError(
            f"unknown cadence {cadence!r}; expected one of {sorted(CADENCE_SECONDS)}"
        ) from None


# ---------------------------------------------------------------------------
# Corpus cache paths
# ---------------------------------------------------------------------------


def _src_dir(slug: str, corpus_dir: Optional[Path] = None) -> Path:
    return (corpus_dir or CORPUS_DIR) / slug


def _out_dir(slug: str, corpus_dir: Optional[Path] = None) -> Path:
    return (corpus_dir or CORPUS_DIR) / "_out" / slug


def _arch_dir(slug: str, corpus_dir: Optional[Path] = None) -> Path:
    return _out_dir(slug, corpus_dir) / "architecture"


def _store_path(slug: str, corpus_dir: Optional[Path] = None) -> Path:
    return _out_dir(slug, corpus_dir) / "index.db"


def _run_dir(slug: str, date: Optional[str] = None, runs_dir: Optional[Path] = None) -> Path:
    return (runs_dir or RUNS_DIR) / slug / (date or _today())


# ---------------------------------------------------------------------------
# fetch: clone/fetch, resolve the ref, record the SHA
# ---------------------------------------------------------------------------


def _git(repo_dir: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo_dir), *args], capture_output=True, text=True, check=check
    )


def _is_shallow(repo_dir: Path) -> bool:
    return _git(repo_dir, "rev-parse", "--is-shallow-repository").stdout.strip() == "true"


def _restore_dirty_tracked_files(src: Path) -> None:
    """Same defence as golden-corpus.py's fetch_corpus: a hard kill mid-run can
    leave a stray edit in a tracked file (for example a mutated fixture from an
    interrupted step); restore it so the next run never analyzes a poisoned
    tree. Untracked files (the store, history/) are left alone."""
    dirty = _git(src, "status", "--porcelain", "--untracked-files=no").stdout.strip()
    if dirty:
        _git(src, "checkout", "--", ".")


def _apply_excludes(src: Path, excludes: list[str]) -> None:
    gitignore = src / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    lines = existing.splitlines()
    cleaned: list[str] = []
    in_block = False
    for line in lines:
        if line.strip() == _EXCLUDE_BEGIN:
            in_block = True
            continue
        if line.strip() == _EXCLUDE_END:
            in_block = False
            continue
        if not in_block:
            cleaned.append(line)
    if excludes:
        cleaned.append(_EXCLUDE_BEGIN)
        cleaned.extend(excludes)
        cleaned.append(_EXCLUDE_END)
    gitignore.write_text("\n".join(cleaned).rstrip("\n") + "\n", encoding="utf-8")


def resolve_ref(repo_url: str, policy: dict) -> tuple[str, str]:
    """Return (ref-to-fetch, description) for `policy.follow`.

    - "pinned": the configured `policy.pin`, no network needed to resolve it.
    - "default-branch": `git ls-remote --symref <repo> HEAD`, which returns the
      branch the remote's HEAD symlinks to without a full clone.
    - "latest-tag": `git ls-remote --tags --sort=-v:refname`, picking the first
      (highest by version-sort) tag name. This is a best-effort ordering for
      semantic-version-shaped tags; the design doc does not specify a stricter
      rule (e.g. creatordate, which `ls-remote` cannot report at all), so
      version-sort is the documented choice here.
    """
    follow = policy.get("follow", "default-branch")
    if follow == "pinned":
        pin = policy.get("pin")
        if not pin:
            raise ValueError("policy.follow is 'pinned' but policy.pin is not set")
        return pin, f"pinned:{pin}"

    if follow == "default-branch":
        out = subprocess.run(
            ["git", "ls-remote", "--symref", repo_url, "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout
        for line in out.splitlines():
            if line.startswith("ref:"):
                ref = line.split()[1]
                branch = ref.rsplit("/", 1)[-1]
                return branch, f"default-branch:{branch}"
        raise RuntimeError(
            f"could not resolve the default branch of {repo_url} (no symref in ls-remote output)"
        )

    if follow == "latest-tag":
        out = subprocess.run(
            ["git", "ls-remote", "--tags", "--sort=-v:refname", repo_url],
            capture_output=True, text=True, check=True,
        ).stdout
        for line in out.splitlines():
            if not line.strip():
                continue
            _sha, ref = line.split("\t", 1)
            if ref.endswith("^{}"):
                continue  # a peeled annotated-tag marker, not the tag itself
            tag = ref[len("refs/tags/"):] if ref.startswith("refs/tags/") else ref
            return tag, f"latest-tag:{tag}"
        raise RuntimeError(f"no tags found for {repo_url}")

    raise ValueError(f"unknown policy.follow: {follow!r}")


def _write_fetch_state(
    slug: str, corpus_dir: Optional[Path], *, policy_follow: str, ref_desc: str, resolved_sha: str
) -> Path:
    path = _out_dir(slug, corpus_dir) / "fetch-state.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    state = {
        "slug": slug,
        "policy_follow": policy_follow,
        "resolved_ref": ref_desc,
        "resolved_sha": resolved_sha,
        "fetched_at": _utc_now_iso(),
    }
    path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def read_fetch_state(slug: str, corpus_dir: Optional[Path] = None) -> Optional[dict]:
    path = _out_dir(slug, corpus_dir) / "fetch-state.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def fetch_corpus(corpus: dict, corpus_dir: Optional[Path] = None, *, force: bool = False) -> tuple[Path, str]:
    """Fetch/refresh the corpus clone, returning (source path, resolved SHA).

    Idempotent like golden-corpus.py's fetch_corpus, including the
    restore-dirty-tracked-files defence. The real difference: a golden corpus
    fetches one pinned SHA once and is done; a demo re-resolves `policy.follow`
    on every call (a branch or tag name can move), so unlike the golden-corpus
    pin check there is no "HEAD already matches, skip the network" short
    circuit for default-branch/latest-tag -- resolving IS the point.

    `policy.history == "full"` means a full clone: no `--depth`. When an
    existing clone is shallow and history policy is "full", it is repaired in
    place with `git fetch --unshallow` rather than left shallow (the whole
    reason this field exists; see the module docstring). The converse is never
    done: a full clone under a "shallow" policy is left full, since re-shallowing
    would only save disk at the cost of a destructive history rewrite for no
    correctness benefit.
    """
    corpus_dir = corpus_dir or CORPUS_DIR
    slug = corpus["slug"]
    repo_url = corpus["subject"]["repo"]
    policy = corpus["policy"]
    full_history = policy.get("history", "full") == "full"
    excludes = policy.get("exclude") or []
    src = _src_dir(slug, corpus_dir)

    ref_name, ref_desc = resolve_ref(repo_url, policy)

    if not force and (src / ".git").exists():
        _restore_dirty_tracked_files(src)
        currently_shallow = _is_shallow(src)
        if full_history and currently_shallow:
            _git(src, "fetch", "--unshallow")
            currently_shallow = False
        fetch_args = ["fetch"]
        # Depth-limit only when the repo is ALREADY shallow and shallow is what
        # policy wants: fetching --depth 1 into an already-full clone would
        # itself shallow it (git truncates history to the fetched tip), which
        # is exactly the reshallow the docstring above says never happens.
        if not full_history and currently_shallow:
            fetch_args += ["--depth", "1"]
        fetch_args += ["origin", ref_name]
        _git(src, *fetch_args)
        _git(src, "checkout", "-q", "--detach", "FETCH_HEAD")
    else:
        if src.exists():
            _rmtree(src)
        src.mkdir(parents=True, exist_ok=True)
        _git(src, "init", "-q")
        _git(src, "remote", "add", "origin", repo_url)
        fetch_args = ["fetch"]
        if not full_history:
            fetch_args += ["--depth", "1"]
        fetch_args += ["origin", ref_name]
        _git(src, *fetch_args)
        _git(src, "checkout", "-q", "--detach", "FETCH_HEAD")

    resolved_sha = _git(src, "rev-parse", "HEAD").stdout.strip()
    _apply_excludes(src, excludes)
    _write_fetch_state(slug, corpus_dir, policy_follow=policy.get("follow", ""), ref_desc=ref_desc, resolved_sha=resolved_sha)
    return src, resolved_sha


# ---------------------------------------------------------------------------
# analyze / enhance: thin subprocess wrappers over analyze.py
# ---------------------------------------------------------------------------


def _snapshot_history(slug: str, out_dir: Path, corpus_dir: Optional[Path] = None) -> None:
    """Copy today's manifest.json into _out/<slug>/history/<date>/ so a later
    `diff` has something to compare a future run against. Gitignored cache only
    (never committed): the committed record of a diff is the diff itself
    (demos/runs/<slug>/<date>/diff.json), not the raw projections either side
    used, which would bloat the repo every week for no reviewing benefit."""
    manifest = out_dir / "manifest.json"
    if not manifest.is_file():
        return
    dest_dir = _out_dir(slug, corpus_dir) / "history" / _today()
    dest_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(manifest, dest_dir / "manifest.json")


def run_analyze(corpus: dict, corpus_dir: Optional[Path] = None) -> float:
    """`analyze.py <src> -o <out> --split --engine v2 --store <per-demo store>`.

    Returns wall time in seconds. `budget.max_wall_minutes` is enforced as a
    subprocess timeout (not specified explicitly in DEMO-PROGRAM.md 4.2, but
    the registry carries the field and section 4.6/7 treat wall time as a real
    constraint to measure and budget against, so bounding it here is the
    natural place).
    """
    slug = corpus["slug"]
    src = _src_dir(slug, corpus_dir)
    if not (src / ".git").exists():
        raise FileNotFoundError(f"no fetched corpus for '{slug}' at {src}; run: fetch {slug}")
    out_dir = _arch_dir(slug, corpus_dir)
    store_path = _store_path(slug, corpus_dir)
    minutes = corpus.get("budget", {}).get("max_wall_minutes")
    timeout_s = float(minutes) * 60 if minutes else None

    cmd = [
        sys.executable, str(ANALYZE_SCRIPT), str(src),
        "-o", str(out_dir), "--split", "--engine", "v2", "--store", str(store_path),
    ]
    t0 = time.perf_counter()
    subprocess.run(cmd, check=True, timeout=timeout_s)
    wall_s = time.perf_counter() - t0
    _snapshot_history(slug, out_dir, corpus_dir)
    return wall_s


def run_enhance(
    corpus: dict,
    corpus_dir: Optional[Path] = None,
    *,
    max_partitions: Optional[int] = None,
    dry_run: bool = False,
) -> int:
    """`analyze.py enhance --update` with the registry's cost ceiling and
    quality threshold. Returns the subprocess exit code (0 success/dry-run, 1 a
    real but non-crashing failure such as a failed partition or an unmet
    quality gate) rather than raising, so a caller can decide what a
    "successful enhance run that failed its own gate" means without catching
    an exception for an expected outcome.

    `--threshold` is not in the DEMO-PROGRAM.md 4.2 one-liner for this
    subcommand, but wiring it from `gates.min_enrichment_score` means the
    quality gate `analyze.py enhance` already computes is directly what
    `validate`'s enrichment gate reads back, instead of re-implementing the
    scorer a second time.
    """
    slug = corpus["slug"]
    root = _src_dir(slug, corpus_dir)
    store_path = _store_path(slug, corpus_dir)
    if not store_path.exists():
        raise FileNotFoundError(f"no fact store for '{slug}' at {store_path}; run: analyze {slug}")
    report_path = _out_dir(slug, corpus_dir) / "enhance-report.json"

    cmd = [
        sys.executable, str(ANALYZE_SCRIPT), "enhance", str(root),
        "--store", str(store_path),
        "--update",
        "--max-cost-usd", str(corpus["budget"]["max_cost_usd"]),
        "--threshold", str(corpus["gates"]["min_enrichment_score"]),
        "--report", str(report_path),
    ]

    # The Enrichment Engine ladder, when the registry asks for it. The Run Report
    # lands in the run directory beside every other artifact of that refresh, so
    # a reader who opens one date opens everything that happened on it.
    enrichment = corpus.get("enrichment") or {}
    if enrichment.get("pipeline") == "ladder":
        run_dir = _run_dir(slug, runs_dir=None) / "enrichment"
        cmd += ["--ladder", "--run-dir", str(run_dir)]
        for key, binding in sorted((enrichment.get("models") or {}).items()):
            cmd += ["--phase-model", f"{key}={binding}"]
        iteration = enrichment.get("iteration") or {}
        if iteration.get("min_rounds") is not None:
            cmd += ["--min-rounds", str(iteration["min_rounds"])]
        if iteration.get("max_rounds") is not None:
            cmd += ["--max-rounds", str(iteration["max_rounds"])]

    if max_partitions is not None:
        cmd += ["--max-partitions", str(max_partitions)]
    if dry_run:
        cmd += ["--dry-run"]

    result = subprocess.run(cmd)
    return result.returncode


def enrichment_run_dir(slug: str, date: Optional[str] = None, runs_dir: Optional[Path] = None) -> Path:
    """Where a ladder run's Run Report lands for one demo and date."""
    return _run_dir(slug, date=date, runs_dir=runs_dir) / "enrichment"


# ---------------------------------------------------------------------------
# validate: the 3.6 checklist + the section 2 graduation gate
# ---------------------------------------------------------------------------

# The full-parse language set, read from analyzer/parsers/PARSERS, which is the
# RUNTIME source of truth rather than a copy of it. A hardcoded mirror drifts,
# and it drifts in the dangerous direction: naming one language too many shrinks
# the measured detect-only share and makes the 25% theater gate easier to pass,
# which is precisely the gate that is supposed to stop us publishing a map that
# is mostly a file listing. tests/test_language_tiers.py keeps the same registry
# honest against the README's documented tiers; this reads the registry itself,
# so the two cannot disagree.
def _language_sets() -> tuple:
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from analyzer.constants import CODE_LANGUAGES as _CODE
    from analyzer.parsers import PARSERS

    return frozenset(PARSERS), frozenset(_CODE)


FULL_PARSE_LANGS, CODE_LANGUAGES = _language_sets()

UPSTREAM_LICENSE_NAMES = ("UPSTREAM-LICENSE.txt", "UPSTREAM-LICENSE", "UPSTREAM-LICENSE.md")

# Gate names whose failure represents a publish blocker in the 5.2 severity
# sense (used by `findings`, not by `validate` itself -- validate treats every
# gate as required).
BLOCKING_GATE_NAMES = {
    "coverage_ledger_complete", "detect_only_line_share",
    "enrichment_quality", "front_door_agrees",
}


@dataclass
class GateResult:
    name: str
    state: str  # PASS | FAIL | NOT_IMPLEMENTED | SKIP
    detail: str = ""

    def to_dict(self) -> dict:
        return {"name": self.name, "state": self.state, "detail": self.detail}


def _skip_if_no_manifest(arch_dir: Path, gate_name: str) -> Optional[GateResult]:
    if not (arch_dir / "manifest.json").is_file():
        return GateResult(gate_name, "SKIP", f"no manifest.json at {arch_dir}; run `analyze <slug>` first")
    return None


def _iter_components(nodes) -> list[dict]:
    out: list[dict] = []
    for node in nodes or []:
        if not isinstance(node, dict):
            continue
        out.append(node)
        out.extend(_iter_components(node.get("children")))
    return out


def gate_split_projection(arch_dir: Path) -> GateResult:
    """3.6: split-mode projection with per-component detail shards."""
    skip = _skip_if_no_manifest(arch_dir, "split_projection")
    if skip:
        return skip
    data_dir = arch_dir / "data"
    shards = list(data_dir.glob("detail-*.json")) if data_dir.is_dir() else []
    if not shards:
        return GateResult("split_projection", "FAIL", f"manifest.json exists but no detail shards under {data_dir}")
    return GateResult("split_projection", "PASS", f"manifest.json + {len(shards)} detail shard(s)")


def gate_coverage_complete(store_path: Path, src: Path) -> GateResult:
    """Section 2 + 3.6: coverage ledger complete, zero unaccounted rows.

    Cross-references a real filesystem walk against the store's coverage
    ledger, exactly the method scripts/benchmark-engine.py's `_ledger_report`
    already proved against VS Code (TASKS.md: "16,482 files walked, EVERY file
    accounted for exactly once, zero unaccounted"). Reused rather than
    reinvented: a pruned directory's single ledger row stands for everything
    beneath it (the pruned-directory ruling), so a file under an
    excluded:skipped_directory / excluded:vendored_repo row (which includes
    .git, per that same ruling) is accounted for by prefix match, not by being
    individually listed.
    """
    if not store_path.is_file():
        return GateResult("coverage_ledger_complete", "SKIP", f"no fact store at {store_path}; run `analyze <slug>` first")

    from analyzer.store import FactStore

    fs = FactStore(str(store_path))
    try:
        coverage = fs.coverage()
        summary = fs.coverage_summary()
    finally:
        fs.close()

    dir_rows = sorted(
        row["path"] for row in coverage
        if row["disposition"].startswith("excluded:skipped_directory")
        or row["disposition"].startswith("excluded:vendored_repo")
    )
    file_rows = {row["path"] for row in coverage if row["path"] not in dir_rows}

    def _under_excluded_dir(rel: str) -> bool:
        return any(rel == d or rel.startswith(d + "/") for d in dir_rows)

    walked = 0
    unaccounted = 0
    examples: list[str] = []
    for dirpath, _dirnames, filenames in os.walk(src):
        for fn in filenames:
            abs_p = Path(dirpath) / fn
            try:
                rel = abs_p.relative_to(src).as_posix()
            except ValueError:
                continue
            walked += 1
            if rel in file_rows or _under_excluded_dir(rel):
                continue
            unaccounted += 1
            if len(examples) < 5:
                examples.append(rel)

    if unaccounted:
        return GateResult(
            "coverage_ledger_complete", "FAIL",
            f"{unaccounted} of {walked} walked files are not in the coverage ledger, e.g. {examples}",
        )
    return GateResult("coverage_ledger_complete", "PASS", f"{walked} files walked, {summary.get('parsed', 0)} parsed, 0 unaccounted")


def gate_detect_only_share(arch_dir: Path, gates_cfg: dict) -> GateResult:
    """Section 2: detect-only languages under `gates.max_detect_only_line_share`
    of counted CODE lines. Full-parse vs detect-only is decided by
    FULL_PARSE_LANGS (see its docstring).

    The denominator is deliberately restricted to `analyzer.constants.CODE_LANGUAGES`
    and is the whole point of the gate. `manifest.stats.languages` counts every
    file type, so on VS Code it is 76% TypeScript and **18% JSON**, plus markdown,
    css, yaml and html. Measuring the detect-only share against that total makes
    JSON and Markdown read as "languages we cannot parse" and yields 21.9%
    against a 25% limit; measuring it against code lines yields **0.10%**.
    PREFLIGHT-MEASUREMENTS.md called this out when the numbers were first taken:
    "Use the code-only figure; the all-lines number is inflated by JSON and config
    and would give a false read."

    Getting this wrong fails safe in the wrong direction. It passes, so nobody
    looks, while sitting three points from a limit it should clear by twenty-five,
    so a subject with a little more JSON would trip a theater gate for having
    documentation."""
    skip = _skip_if_no_manifest(arch_dir, "detect_only_line_share")
    if skip:
        return skip
    manifest_path = arch_dir / "manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("detect_only_line_share", "FAIL", f"manifest.json is not valid JSON: {exc}")

    languages = (manifest.get("stats") or {}).get("languages") or {}
    all_lines = sum(languages.values())
    code = {k: v for k, v in languages.items() if k in CODE_LANGUAGES}
    total = sum(code.values())
    if total == 0:
        return GateResult("detect_only_line_share", "PASS", "no code lines counted")
    full = sum(v for k, v in code.items() if k in FULL_PARSE_LANGS)
    detect_only = total - full
    share = detect_only / total
    limit = gates_cfg.get("max_detect_only_line_share")
    if limit is None:
        return GateResult("detect_only_line_share", "FAIL", "gates.max_detect_only_line_share is not set in the registry")
    state = "PASS" if share <= limit else "FAIL"
    non_code = all_lines - total
    return GateResult(
        "detect_only_line_share", state,
        f"{share:.2%} detect-only ({detect_only:,} of {total:,} code lines, "
        f"limit {limit:.0%}); {non_code:,} non-code lines excluded from the denominator",
    )


def gate_enrichment_quality(slug: str, corpus_dir: Optional[Path], gates_cfg: dict) -> GateResult:
    """Section 2 + 3.6, upgraded to the TRUTH instrument.

    The form scorer is a sanity FLOOR, not the gate. The calibration measured 83
    of 99 components scoring exactly 85.0 on it while nothing checked whether one
    claim was true; a gate that reads only that number certifies shape and calls
    it quality.

    So when a ladder Run Report exists, this reads what the truth instrument
    actually produced:

      * the contract census: nothing may still be asking to climb, because an
        item in the escalate state is unfinished work rather than a gap;
      * the adjudication disagreement rate: how many sampled claims independent
        adjudication would not stand behind;
      * the verify verdicts: the S2 identity surface.

    And it keeps the NOT_IMPLEMENTED discipline exactly. A ladder run whose
    adjudication sampled NOTHING has no truth instrument, and reporting PASS on
    the form floor alone would be the precise failure this gate exists to
    prevent: a green light with nothing behind it. That case is
    NOT_IMPLEMENTED, loudly, never a silent pass.

    A registry entry with no ladder falls back to the classic bulk report, which
    is what every entry did before the ladder existed.
    """
    ladder_report = enrichment_run_dir(slug) / "report.json"
    if ladder_report.is_file():
        return _gate_from_run_report(ladder_report, gates_cfg)

    report_path = _out_dir(slug, corpus_dir) / "enhance-report.json"
    if not report_path.is_file():
        return GateResult("enrichment_quality", "SKIP", f"no enrichment report at {report_path}; run `enhance <slug>` first")
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("enrichment_quality", "FAIL", f"enhance-report.json is not valid JSON: {exc}")

    failed = report.get("failed_partitions") or []
    if failed:
        return GateResult("enrichment_quality", "FAIL", f"{len(failed)} failed partition(s): {failed}")

    scorer_pass = report.get("scorer_pass")
    threshold = gates_cfg.get("min_enrichment_score")
    if scorer_pass is None:
        return GateResult("enrichment_quality", "SKIP", "enrichment report has no scorer result (a --dry-run report); run `enhance <slug>` for real")
    if scorer_pass is False:
        return GateResult("enrichment_quality", "FAIL", f"quality gate failed: {report.get('scorer_summary')}")
    return GateResult("enrichment_quality", "PASS", f"quality gate passed at threshold {threshold}: {report.get('scorer_summary')}")


# Truth-instrument bounds. Deliberately explicit rather than buried in the gate,
# because these two numbers are what "good enough to publish" means in practice
# and they should be arguable in one place.
MIN_GROUNDED_FRACTION = 0.80
MAX_DISAGREEMENT_RATE = 0.20


def _gate_from_run_report(report_path: Path, gates_cfg: dict) -> GateResult:
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("enrichment_quality", "FAIL", f"Run Report is not valid JSON: {exc}")

    identity = report.get("identity") or {}
    if identity.get("dry_run"):
        return GateResult(
            "enrichment_quality", "SKIP",
            "the Run Report is from a --dry-run ladder (no model was invoked); "
            "run `enhance <slug>` for real",
        )

    census = report.get("census") or {}
    total = int(census.get("total") or 0)
    if not total:
        return GateResult(
            "enrichment_quality", "NOT_IMPLEMENTED",
            "the ladder produced no contract census, so the truth instrument has "
            "nothing to read; this is reported rather than passed on the form floor",
        )

    unresolved = census.get("unresolved") or []
    if unresolved:
        return GateResult(
            "enrichment_quality", "FAIL",
            f"{len(unresolved)} item(s) were still asking to climb when the ladder "
            f"stopped: {unresolved[:5]}. That is unfinished work, not an honest gap",
        )

    adjudication = report.get("adjudication") or {}
    sampled = int(adjudication.get("checked") or 0)
    rate = adjudication.get("disagreement_rate")
    if not sampled or rate is None:
        return GateResult(
            "enrichment_quality", "NOT_IMPLEMENTED",
            "no grounding spot-checks were run, so the disagreement rate is "
            "undefined rather than zero and nothing has checked whether the "
            "claims are supported by their own evidence. The form scorer alone "
            "is a floor, not a quality verdict",
        )

    grounded_fraction = float(census.get("grounded_fraction") or 0.0)
    problems: list[str] = []
    if grounded_fraction < MIN_GROUNDED_FRACTION:
        problems.append(
            f"only {grounded_fraction:.1%} of items grounded "
            f"(floor {MIN_GROUNDED_FRACTION:.0%})"
        )
    if float(rate) > MAX_DISAGREEMENT_RATE:
        problems.append(
            f"adjudication would not stand behind {float(rate):.1%} of the "
            f"{sampled} claims it sampled (ceiling {MAX_DISAGREEMENT_RATE:.0%})"
        )

    # The universal gates the determination already answered mechanically are
    # read back rather than recomputed, so the gate and the Run Report cannot
    # disagree about the same run.
    unmet = [
        c.get("criterion_id")
        for c in (report.get("criteria") or [])
        if c.get("verdict") == "unmet"
    ]
    if unmet:
        problems.append("criteria not met: " + ", ".join(str(c) for c in unmet))

    identity_pass = (report.get("adjudication") or {}).get("identity") or {}
    identity_note = ""
    if identity_pass:
        verdicts = identity_pass.get("verdicts") or {}
        identity_note = (
            f"; identity verdicts {', '.join(f'{k}={v}' for k, v in sorted(verdicts.items()))}"
            if verdicts else ""
        )

    summary = (
        f"{census.get('grounded', 0)}/{total} grounded "
        f"({grounded_fraction:.1%}), disagreement {float(rate):.1%} over "
        f"{sampled} sampled claim(s){identity_note}"
    )
    if problems:
        return GateResult("enrichment_quality", "FAIL", "; ".join(problems) + f" [{summary}]")
    return GateResult("enrichment_quality", "PASS", summary)


def gate_sbom_present(arch_dir: Path) -> GateResult:
    """3.6: SBOM."""
    skip = _skip_if_no_manifest(arch_dir, "sbom_present")
    if skip:
        return skip
    if (arch_dir / "sbom.json").is_file():
        return GateResult("sbom_present", "PASS", "sbom.json present")
    return GateResult("sbom_present", "FAIL", f"no sbom.json in {arch_dir}")


def gate_cra_readiness_present(arch_dir: Path) -> GateResult:
    """3.6: CRA readiness artifact."""
    skip = _skip_if_no_manifest(arch_dir, "cra_readiness_present")
    if skip:
        return skip
    if (arch_dir / "cra-readiness.json").is_file():
        return GateResult("cra_readiness_present", "PASS", "cra-readiness.json present")
    return GateResult("cra_readiness_present", "FAIL", f"no cra-readiness.json in {arch_dir}")


def gate_front_door_agrees(arch_dir: Path) -> GateResult:
    """Section 2 + 3.6: front door agrees with the manifest (the S3 class).

    S3 (frontdoor.py's own docstring) was ai.json asserting `enriched: false`
    while the manifest carried ai_enhance on nearly every component, because a
    later merge step edited the manifest without calling `refresh_front_door`.
    This gate re-derives the true enrichment state from the manifest and
    compares it to ai.json's claim, and confirms every endpoint ai.json lists
    (other than templated `<...>` shard patterns) actually exists in the
    bundle. It does not (yet) re-verify every `manifest_sections[*].present`
    flag individually; the enriched-flag mismatch is the exact defect class S3
    was, and the endpoint-existence check is link integrity.
    """
    skip = _skip_if_no_manifest(arch_dir, "front_door_agrees")
    if skip:
        return skip
    ai_json_path = arch_dir / "ai.json"
    if not ai_json_path.is_file():
        return GateResult("front_door_agrees", "FAIL", f"no ai.json in {arch_dir}")
    try:
        manifest = json.loads((arch_dir / "manifest.json").read_text(encoding="utf-8"))
        ai_json = json.loads(ai_json_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("front_door_agrees", "FAIL", f"could not read manifest.json/ai.json: {exc}")

    manifest_enriched = bool(manifest.get("ai_enhance")) or any(
        c.get("ai_enhance") for c in _iter_components(manifest.get("components"))
    )
    claimed_enriched = (ai_json.get("dataset") or {}).get("enriched")
    if claimed_enriched != manifest_enriched:
        return GateResult(
            "front_door_agrees", "FAIL",
            f"ai.json claims dataset.enriched={claimed_enriched!r} but the manifest's actual "
            f"enrichment state is {manifest_enriched!r} (the S3 defect class)",
        )

    missing = [
        e.get("path") for e in (ai_json.get("endpoints") or [])
        if "<" not in (e.get("path") or "") and not (arch_dir / e["path"]).exists()
    ]
    if missing:
        return GateResult("front_door_agrees", "FAIL", f"ai.json lists endpoints that do not exist on disk: {missing}")

    return GateResult("front_door_agrees", "PASS", "ai.json's enrichment claim and endpoint list agree with the manifest and bundle")


def gate_search_index(arch_dir: Path) -> GateResult:
    """3.6: search index including endpoints.

    Scope note: analyzer/project/search_shards.py indexes `component`, `file`,
    `symbol`, and `enrichment` ref_kinds; there is no distinct `endpoint`
    ref_kind today, so this checks that the search index exists and is
    non-empty rather than asserting endpoint entries specifically, which the
    current search index cannot promise. That gap is real; it is not silently
    covered up by this gate passing (see the harness report for detail).
    """
    skip = _skip_if_no_manifest(arch_dir, "search_index_present")
    if skip:
        return skip
    search_manifest = arch_dir / "search" / "manifest.json"
    if not search_manifest.is_file():
        return GateResult("search_index_present", "FAIL", f"no search/manifest.json in {arch_dir}")
    try:
        data = json.loads(search_manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("search_index_present", "FAIL", f"search/manifest.json is not valid JSON: {exc}")
    total = data.get("total", 0)
    if not total:
        return GateResult("search_index_present", "FAIL", "search index is empty (total=0)")
    return GateResult("search_index_present", "PASS", f"{total} search entries across {len(data.get('shards', []))} shard(s)")


def gate_publication_metadata(arch_dir: Path, fetch_state: Optional[dict]) -> GateResult:
    """3.6: publication.json with showcase framing, exact commit, snapshot date.

    Reuses scripts/validate-publication.py's own validate_doc/validate_bundle
    (loaded the same dynamic-import way golden-corpus.py loads projection-diff)
    rather than re-implementing the obligation checks. `publication.json`
    itself is not generated by this harness -- no subcommand in DEMO-PROGRAM.md
    4.2 creates it, so it is treated as a hand-authored artifact placed in the
    bundle before validate/deploy, same as the templates in
    docs/publication/templates/ already assume.
    """
    skip = _skip_if_no_manifest(arch_dir, "publication_metadata")
    if skip:
        return skip
    pub_path = arch_dir / "publication.json"
    if not pub_path.is_file():
        return GateResult(
            "publication_metadata", "FAIL",
            f"no publication.json in {arch_dir}; copy docs/publication/templates/"
            f"publication.showcase.json and fill it in",
        )
    try:
        doc = json.loads(pub_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return GateResult("publication_metadata", "FAIL", f"{pub_path} is not valid JSON: {exc}")

    vp = _load_validate_publication()
    errors = vp.validate_doc(doc)
    if not errors:
        errors = vp.validate_bundle(arch_dir, doc)
    if errors:
        return GateResult("publication_metadata", "FAIL", "; ".join(errors))

    if fetch_state and fetch_state.get("resolved_sha"):
        commit = str(((doc.get("subject") or {}).get("commit")) or "")
        resolved = fetch_state["resolved_sha"]
        if commit and not (resolved.startswith(commit) or commit.startswith(resolved)):
            return GateResult(
                "publication_metadata", "FAIL",
                f"publication.json subject.commit {commit!r} does not match the resolved fetch SHA {resolved!r}",
            )

    return GateResult("publication_metadata", "PASS", f"publication.json valid, subject={(doc.get('subject') or {}).get('name')!r}")


def gate_upstream_license(arch_dir: Path) -> GateResult:
    """3.6 + section 2: upstream LICENSE shipped in the bundle."""
    skip = _skip_if_no_manifest(arch_dir, "upstream_license_shipped")
    if skip:
        return skip
    if any((arch_dir / name).is_file() for name in UPSTREAM_LICENSE_NAMES):
        return GateResult("upstream_license_shipped", "PASS", "upstream LICENSE present in the bundle")
    return GateResult(
        "upstream_license_shipped", "FAIL",
        f"none of {list(UPSTREAM_LICENSE_NAMES)} found in {arch_dir}; the viewer redistributes "
        f"upstream README/doc text, so the license notice must travel with it (1.2)",
    )


def gate_classification_accuracy_audit() -> GateResult:
    """Section 2 (5.3): classification sample audit at or above its floor.

    THE explicit example from the task: this instrument does not exist.
    DEMO-PROGRAM.md 5.3 specifies its shape (sample N components, compare each
    declared fact against its own recorded evidence, score) but says it is not
    built. There is nothing to compute, so this can never legitimately PASS or
    FAIL; reporting anything but NOT_IMPLEMENTED here would be exactly the
    "gate that silently passes, and is believed" failure mode this harness is
    built to refuse.
    """
    return GateResult(
        "classification_accuracy_audit", "NOT_IMPLEMENTED",
        "DEMO-PROGRAM.md 5.3 specifies this instrument but it is not built. "
        "Cannot PASS or FAIL until it exists.",
    )


def gate_license_review_recorded(corpus: dict) -> GateResult:
    """Section 2 (6.1): license review passed (the human-recorded half).

    6.1 item 7 calls for a recorded reviewer, date, SPDX identifier and the
    commit reviewed. That is now a real registry field, `license_review`, a
    second documented addition to the 4.1 schema alongside `policy.history`,
    and the record it points at lives under docs/publication/license-reviews/.

    The published track additionally requires the owner's countersignature.
    A license review is the legal surface of publishing someone else's code,
    and a review signed only by the tool that wants to publish is not the
    check 6.1 is asking for. Missing countersignature is a FAIL with a named
    reason, never a silent pass and never NOT_IMPLEMENTED: the instrument
    exists, the obligation is simply unmet.
    """
    review = corpus.get("license_review")
    if not isinstance(review, dict):
        return GateResult(
            "license_review_recorded", "FAIL",
            "no 'license_review' block in the registry entry; DEMO-PROGRAM.md 6.1 "
            "item 7 requires a recorded reviewer, date, SPDX identifier and commit",
        )
    missing = [k for k in ("reviewer", "date", "spdx", "record") if not review.get(k)]
    if missing:
        return GateResult(
            "license_review_recorded", "FAIL",
            f"license_review is missing {missing}",
        )
    record = REPO_ROOT / str(review["record"])
    if not record.is_file():
        return GateResult(
            "license_review_recorded", "FAIL",
            f"license_review.record points at {record}, which does not exist",
        )
    if corpus.get("track") == "published" and not review.get("countersigned_by_owner"):
        return GateResult(
            "license_review_recorded", "FAIL",
            f"license review recorded by {review['reviewer']!r} on {review['date']} "
            f"({review['spdx']}, {review['record']}) but not countersigned by the "
            f"owner; a published demo redistributes upstream text and the sign-off "
            f"is the owner's to give",
        )
    return GateResult(
        "license_review_recorded", "PASS",
        f"{review['spdx']} reviewed by {review['reviewer']!r} on {review['date']} "
        f"({review['record']})",
    )


def gate_consent_triage(consent: dict) -> GateResult:
    """Section 2: sensitivity triage clean, or outreach completed
    (DISCLOSURE-POLICY.md). Computed straight from the registry's `consent`
    block: not required is a clean pass; required is a pass only once
    `consent.state` records a cleared outcome."""
    required = consent.get("required")
    state = consent.get("state")
    if not required:
        return GateResult("consent_triage", "PASS", f"consent not required (state={state!r})")
    if state in ("approved", "cleared", "granted"):
        return GateResult("consent_triage", "PASS", f"consent recorded as {state!r}")
    return GateResult(
        "consent_triage", "FAIL",
        f"consent.required is true but consent.state is {state!r}, not a cleared "
        f"state; see DISCLOSURE-POLICY.md",
    )


def run_gates(corpus: dict, *, corpus_dir: Optional[Path] = None) -> list[GateResult]:
    """Compute every gate for one demo. Pure (no printing), so it is directly
    testable and directly reusable by `findings`."""
    slug = corpus["slug"]
    arch_dir = _arch_dir(slug, corpus_dir)
    store_path = _store_path(slug, corpus_dir)
    src = _src_dir(slug, corpus_dir)
    fetch_state = read_fetch_state(slug, corpus_dir)
    gates_cfg = corpus.get("gates", {})

    return [
        gate_split_projection(arch_dir),
        gate_coverage_complete(store_path, src),
        gate_detect_only_share(arch_dir, gates_cfg),
        gate_enrichment_quality(slug, corpus_dir, gates_cfg),
        gate_sbom_present(arch_dir),
        gate_cra_readiness_present(arch_dir),
        gate_front_door_agrees(arch_dir),
        gate_search_index(arch_dir),
        gate_publication_metadata(arch_dir, fetch_state),
        gate_upstream_license(arch_dir),
        gate_classification_accuracy_audit(),
        gate_license_review_recorded(corpus),
        gate_consent_triage(corpus.get("consent", {})),
    ]


def overall_ok(results: list[GateResult], allow_unimplemented: bool) -> bool:
    """A run is ok only when every gate PASSes, with one narrow exception:
    under --allow-unimplemented, a NOT_IMPLEMENTED gate is tolerated (it is
    reported, just not blocking). FAIL and SKIP are never tolerated by the
    flag: SKIP means a precondition step has not run yet, which is not the
    same problem --allow-unimplemented exists to solve, and FAIL means the
    subject genuinely does not meet the bar."""
    for r in results:
        if r.state == "PASS":
            continue
        if r.state == "NOT_IMPLEMENTED" and allow_unimplemented:
            continue
        return False
    return True


def _write_validate_record(
    slug: str, results: list[GateResult], ok: bool, *, runs_dir: Optional[Path] = None, date: Optional[str] = None
) -> Path:
    run_dir = _run_dir(slug, date, runs_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / "validate.json"
    payload = {
        "schema": "solution-explorer/demo-validate/v1",
        "slug": slug,
        "date": date or _today(),
        "ok": ok,
        "gates": [r.to_dict() for r in results],
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def read_validate_record(slug: str, runs_dir: Optional[Path] = None, date: Optional[str] = None) -> Optional[dict]:
    path = _run_dir(slug, date, runs_dir) / "validate.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


# ---------------------------------------------------------------------------
# diff: projection diff against the previous run
# ---------------------------------------------------------------------------


def previous_projection(slug: str, corpus_dir: Optional[Path] = None, *, before: Optional[str] = None) -> Optional[Path]:
    before = before or _today()
    history_dir = _out_dir(slug, corpus_dir) / "history"
    if not history_dir.is_dir():
        return None
    dates = sorted(p.name for p in history_dir.iterdir() if p.is_dir() and p.name < before)
    if not dates:
        return None
    candidate = history_dir / dates[-1] / "manifest.json"
    return candidate if candidate.is_file() else None


def run_diff(corpus: dict, corpus_dir: Optional[Path] = None, runs_dir: Optional[Path] = None) -> Optional[dict]:
    """Diff the current projection against the most recent prior one recorded
    in history/. Returns None (and writes nothing) when there is no baseline
    yet -- the caller decides how to report that, matching the spec's "no
    previous run is not an error"."""
    slug = corpus["slug"]
    current = _arch_dir(slug, corpus_dir) / "manifest.json"
    if not current.is_file():
        raise FileNotFoundError(f"no analysis output for '{slug}'; run: analyze {slug}")
    previous = previous_projection(slug, corpus_dir)
    if previous is None:
        return None
    pd = _load_projection_diff()
    diff = pd.diff_projections(pd.load_projection(previous), pd.load_projection(current))
    out_path = _run_dir(slug, runs_dir=runs_dir) / "diff.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(diff, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return diff


# ---------------------------------------------------------------------------
# findings: the 5.1 machine gates -> findings.json (no GitHub issues here)
# ---------------------------------------------------------------------------


def finding_fingerprint(slug: str, check: str, detail: str) -> str:
    """`demo-finding:<slug>:<check>:<hash>` per 5.2, stable across runs for the
    same (slug, check, detail) and different whenever any of them differ."""
    digest = hashlib.sha256(detail.encode("utf-8")).hexdigest()[:12]
    return f"demo-finding:{slug}:{check}:{digest}"


def _zero_symbol_findings(slug: str, corpus_dir: Optional[Path]) -> list[dict]:
    """5.1: zero-symbol components in a full-parse language (a parser finding)."""
    arch_dir = _arch_dir(slug, corpus_dir)
    manifest_path = arch_dir / "manifest.json"
    if not manifest_path.is_file():
        return []
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    index = manifest.get("component_detail_index") or {}
    zero_ids = [
        c["id"] for c in _iter_components(manifest.get("components"))
        if c.get("language") in FULL_PARSE_LANGS
        and (index.get(c.get("id")) or {}).get("symbolCount", 0) == 0
        and c.get("id") in index
    ]
    if not zero_ids:
        return []
    detail = f"{len(zero_ids)} full-parse-language component(s) with zero symbols, e.g. {sorted(zero_ids)[:5]}"
    return [{
        "check": "zero_symbol_full_parse_components",
        "severity": "finding",
        "summary": detail,
        "fingerprint": finding_fingerprint(slug, "zero_symbol_full_parse_components", detail),
    }]


def _orphan_share_finding(slug: str, corpus_dir: Optional[Path]) -> list[dict]:
    """5.1: orphan share, components with no relationships (a relationship-
    inference finding). No numeric floor is given in DEMO-PROGRAM.md for this
    one (unlike coverage/detect-only/enrichment, it is a finding, not a
    graduation gate), so 10% is a documented, conservative noise floor below
    which it is not worth a finding every single week."""
    arch_dir = _arch_dir(slug, corpus_dir)
    manifest_path = arch_dir / "manifest.json"
    if not manifest_path.is_file():
        return []
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    ids = [c["id"] for c in _iter_components(manifest.get("components")) if c.get("id")]
    if not ids:
        return []
    involved: set = set()
    for rel in manifest.get("relationships") or []:
        involved.add(rel.get("source"))
        involved.add(rel.get("target"))
    orphans = [cid for cid in ids if cid not in involved]
    share = len(orphans) / len(ids)
    if share <= 0.10:
        return []
    detail = f"{len(orphans)} of {len(ids)} components ({share:.0%}) have no relationships"
    return [{
        "check": "orphan_component_share",
        "severity": "finding",
        "summary": detail,
        "fingerprint": finding_fingerprint(slug, "orphan_component_share", f"{round(share, 2)}"),
    }]


_PAGES_FREE_FILE_LIMIT = 20_000
_SHARD_WARN_FRACTION = 0.8


def _shard_count_finding(slug: str, corpus_dir: Optional[Path]) -> list[dict]:
    """5.1: shard count and manifest size against hosting limits (a
    scalability finding). Warns at 80% of the Cloudflare Pages free-plan
    20,000-files-per-site limit (4.4), blocks (severity "blocker") at 100%."""
    arch_dir = _arch_dir(slug, corpus_dir)
    if not arch_dir.is_dir():
        return []
    file_count = sum(1 for p in arch_dir.rglob("*") if p.is_file())
    warn_at = int(_PAGES_FREE_FILE_LIMIT * _SHARD_WARN_FRACTION)
    if file_count < warn_at:
        return []
    detail = f"{file_count} files in the deploy bundle, approaching the Cloudflare Pages free-plan limit of {_PAGES_FREE_FILE_LIMIT}"
    return [{
        "check": "hosting_file_budget",
        "severity": "blocker" if file_count >= _PAGES_FREE_FILE_LIMIT else "finding",
        "summary": detail,
        "fingerprint": finding_fingerprint(slug, "hosting_file_budget", f"{file_count // 1000}k"),
    }]


def compute_findings(corpus: dict, *, corpus_dir: Optional[Path] = None) -> list[dict]:
    """The 5.1 machine-gate findings this harness can compute cheaply and
    deterministically today: every FAILing validate gate (which already covers
    unaccounted ledger rows, detect-only share, enrichment failures/quality,
    and front-door disagreement), plus zero-symbol components, orphan share,
    and the hosting file budget. NOT covered here (documented, not hidden):
    staleness surviving a refresh, and wall time/peak memory/store size versus
    last week -- both need a time series this harness's history/ cache does
    not yet retain beyond the single previous projection `diff` uses.
    """
    slug = corpus["slug"]
    findings: list[dict] = []
    for r in run_gates(corpus, corpus_dir=corpus_dir):
        if r.state != "FAIL":
            continue
        severity = "blocker" if r.name in BLOCKING_GATE_NAMES else "finding"
        findings.append({
            "check": r.name,
            "severity": severity,
            "summary": f"{r.name}: {r.detail}",
            "fingerprint": finding_fingerprint(slug, r.name, r.detail),
        })
    findings.extend(_zero_symbol_findings(slug, corpus_dir))
    findings.extend(_orphan_share_finding(slug, corpus_dir))
    findings.extend(_shard_count_finding(slug, corpus_dir))
    return findings


# ---------------------------------------------------------------------------
# report: the run record, JSON and markdown
# ---------------------------------------------------------------------------


def build_report(corpus: dict, *, corpus_dir: Optional[Path] = None, runs_dir: Optional[Path] = None, date: Optional[str] = None) -> dict:
    slug = corpus["slug"]
    date = date or _today()
    arch_dir = _arch_dir(slug, corpus_dir)
    manifest_path = arch_dir / "manifest.json"
    fetch_state = read_fetch_state(slug, corpus_dir) or {}
    validate_record = read_validate_record(slug, runs_dir, date)

    stats: dict = {}
    coverage_summary: dict = {}
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            stats = manifest.get("stats") or {}
            coverage_summary = (manifest.get("coverage") or {}).get("summary") or {}
        except (OSError, json.JSONDecodeError):
            pass

    status = "ok" if (validate_record and validate_record.get("ok")) else "incomplete"

    return {
        "schema": "solution-explorer/demo-run-report/v1",
        "slug": slug,
        "date": date,
        "status": status,
        "subject": corpus["subject"],
        "resolved_ref": fetch_state.get("resolved_ref"),
        "resolved_sha": fetch_state.get("resolved_sha"),
        "stats": {
            "total_components": stats.get("total_components"),
            "total_files": stats.get("total_files"),
            "total_lines": stats.get("total_lines"),
        },
        "coverage_summary": coverage_summary,
        "gates": (validate_record or {}).get("gates", []),
        "hosting": corpus["hosting"],
    }


def render_report_markdown(report: dict) -> str:
    lines = [
        f"# {report['subject']['name']} demo run: {report['date']}",
        "",
        f"- slug: `{report['slug']}`",
        f"- status: **{report['status']}**",
        f"- resolved commit: `{report.get('resolved_sha') or 'unknown'}` ({report.get('resolved_ref') or 'unresolved'})",
        f"- hosting: {report['hosting'].get('url')}",
        "",
        "## Stats",
        "",
    ]
    for key, value in report.get("stats", {}).items():
        lines.append(f"- {key}: {value}")
    lines += ["", "## Coverage summary", ""]
    for disp, count in report.get("coverage_summary", {}).items():
        lines.append(f"- {disp}: {count}")
    lines += ["", "## Gates", ""]
    for gate in report.get("gates", []):
        lines.append(f"- **{gate.get('state')}** {gate.get('name')}: {gate.get('detail')}")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# hub: the generated static site
# ---------------------------------------------------------------------------


def last_successful_run(slug: str, runs_dir: Optional[Path] = None) -> Optional[dict]:
    """The most recent report.json whose validate gate declared `ok`, else
    None. Iterates date directories in ascending sorted (ISO date) order so the
    last match found is the most recent."""
    runs_dir = runs_dir or RUNS_DIR
    slug_dir = runs_dir / slug
    if not slug_dir.is_dir():
        return None
    best: Optional[dict] = None
    for date_dir in sorted(p for p in slug_dir.iterdir() if p.is_dir()):
        report_path = date_dir / "report.json"
        if not report_path.is_file():
            continue
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if report.get("status") == "ok":
            best = report
    return best


def is_due(corpus: dict, runs_dir: Optional[Path] = None, *, now: Optional[datetime] = None) -> bool:
    now = now or datetime.now(timezone.utc)
    last = last_successful_run(corpus["slug"], runs_dir)
    if last is None:
        return True
    last_date_str = last.get("date")
    if not last_date_str:
        return True
    last_date = datetime.fromisoformat(last_date_str).replace(tzinfo=timezone.utc)
    return (now - last_date).total_seconds() >= cadence_period_seconds(corpus["cadence"])


def build_hub_html(corpora: list[dict], *, runs_dir: Optional[Path] = None) -> str:
    """Plain, self-contained HTML: no external assets, no build step, per 4.4.
    Carries per demo: subject, license, upstream commit, snapshot date, size
    and coverage stats, last successful refresh date, and a link -- plus the
    honest unofficial/not-affiliated framing and the 5.4 feedback path."""
    runs_dir = runs_dir or RUNS_DIR
    esc = html.escape
    rows = []
    for corpus in corpora:
        slug = corpus["slug"]
        subject = corpus["subject"]
        last = last_successful_run(slug, runs_dir)
        commit = (last or {}).get("resolved_sha") or ""
        commit_short = commit[:12] if commit else "never refreshed"
        snapshot = (last or {}).get("date") or "never"
        stats = (last or {}).get("stats") or {}
        coverage = (last or {}).get("coverage_summary") or {}
        parsed = coverage.get("parsed")
        rows.append(
            "<tr>"
            f'<td><a href="{esc(corpus["hosting"]["url"])}">{esc(subject["name"])}</a></td>'
            f"<td>{esc(subject['license'])}</td>"
            f"<td><code>{esc(commit_short)}</code></td>"
            f"<td>{esc(snapshot)}</td>"
            f"<td>{esc(str(stats.get('total_files', '?')))} files, {esc(str(stats.get('total_lines', '?')))} lines</td>"
            f"<td>{esc(str(parsed) if parsed is not None else '?')} parsed</td>"
            "</tr>"
        )
    table_rows = "\n      ".join(rows) if rows else '<tr><td colspan="6">No demos registered yet.</td></tr>'

    feedback_url = (
        "https://github.com/sirfifer/solution-explorer/issues/new"
        "?template=demo-feedback.md&title=Demo+feedback"
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SysCorpus demo showcase</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         margin: 0; padding: 2rem; background: #0b0f14; color: #e6edf3; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  .framing {{ max-width: 60rem; color: #9fb0c0; line-height: 1.5; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1.5rem; }}
  th, td {{ text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #22303c; }}
  th {{ color: #9fb0c0; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; }}
  a {{ color: #58a6ff; }}
  code {{ font-family: ui-monospace, SFMono-Regular, monospace; }}
  footer {{ margin-top: 2rem; color: #6b7c8c; font-size: 0.85rem; }}
</style>
</head>
<body>
  <h1>SysCorpus demo showcase</h1>
  <p class="framing">
    Unofficial architecture maps of real, well-known open-source projects,
    generated by solution-explorer from public source. Not affiliated with or
    endorsed by any project listed here. Every demo is refreshed on its own
    cadence from upstream and published only after passing this program's
    validation gates; known gaps are declared inside the viewer, never papered
    over. See something wrong?
    <a href="{esc(feedback_url)}">Tell us</a>.
  </p>
  <table>
    <thead>
      <tr><th>Subject</th><th>License</th><th>Commit</th><th>Last successful refresh</th><th>Size</th><th>Coverage</th></tr>
    </thead>
    <tbody>
      {table_rows}
    </tbody>
  </table>
  <footer>Generated by scripts/demo-site.py hub from demos/registry/ and demos/runs/.</footer>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# bundle: assemble the DEPLOYABLE artifact
# ---------------------------------------------------------------------------
#
# The projection output directory is NOT a deployable site. It is data:
# manifest.json, data/, search/, ai.json, llms.txt. Deploying it directly would
# publish the raw architecture JSON with no viewer to read it and, far worse,
# with no `functions/_middleware.js`, which means no preview gate at all. A
# "private preview" assembled that way is fully public, which is exactly what
# DISCLOSURE-POLICY.md step 3 forbids ("Deploy gated, never public.
# Client-side-only gating is theater and is not acceptable").
#
# DEMO-PROGRAM.md 4.2 does not list a bundle step between `analyze` and
# `deploy`; that is a gap in the written design, recorded here rather than
# papered over. This is the missing step, and it mirrors what action.yml already
# does in CI: projection into viewer/public/architecture, viewer build, deploy
# the built dist.


def _bundle_dir(slug: str, corpus_dir: Optional[Path] = None) -> Path:
    return _out_dir(slug, corpus_dir) / "bundle"


VIEWER_DIR = REPO_ROOT / "viewer"
PREVIEW_GATE_MIDDLEWARE = REPO_ROOT / "infrastructure" / "preview-gate" / "_middleware.js"

# Upstream files worth carrying into the bundle beside UPSTREAM-LICENSE.txt.
# LICENSE-REVIEW.md step 4 asks for the NOTICE analogue; VS Code ships
# ThirdPartyNotices.txt rather than a file literally called NOTICE.
UPSTREAM_LICENSE_CANDIDATES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING")
UPSTREAM_NOTICE_CANDIDATES = ("NOTICE", "NOTICE.txt", "ThirdPartyNotices.txt")


def _find_first(src: Path, names: tuple) -> Optional[Path]:
    for name in names:
        candidate = src / name
        if candidate.is_file():
            return candidate
    return None


def assemble_bundle(
    corpus: dict,
    *,
    corpus_dir: Optional[Path] = None,
    build: bool = True,
) -> Path:
    """Assemble the deployable bundle for ``corpus`` and return its path.

    Steps, in the order action.yml does them:

      1. copy the split projection into viewer/public/architecture/
      2. build the viewer (vite) into viewer/dist
      3. copy viewer/dist to the bundle directory
      4. install the preview gate as functions/_middleware.js
      5. ship the upstream LICENSE as UPSTREAM-LICENSE.txt, plus any NOTICE
      6. carry publication.json through if the projection produced one

    ``build=False`` skips the npm build and reuses an existing viewer/dist,
    which is what the tests use; it never skips steps 4 and 5, because those are
    the obligations, not the expensive part.
    """
    slug = corpus["slug"]
    arch_dir = _arch_dir(slug, corpus_dir)
    if not (arch_dir / "manifest.json").is_file():
        raise RuntimeError(f"no projection at {arch_dir}; run: analyze {slug}")

    bundle = _bundle_dir(slug, corpus_dir)

    # 1. build the viewer AS-IS. Deliberately NOT by copying the projection into
    # viewer/public/architecture first, which is the obvious move and is wrong:
    # that directory is 259 TRACKED files (the committed UnaMentis dataset), so
    # writing a subject's projection over it would destroy repository content and
    # produce an enormous spurious diff. action.yml sidesteps this in CI by
    # building a copy of the viewer under .solution-explorer/. Here the projection
    # is swapped into the BUILT output instead, at step 3, which touches nothing
    # tracked and costs only a build against the placeholder dataset.
    if build:
        subprocess.run(["npm", "run", "build"], cwd=str(VIEWER_DIR), check=True)

    dist = VIEWER_DIR / "dist"
    if not (dist / "index.html").is_file():
        raise RuntimeError(
            f"viewer build produced no index.html at {dist}; a bundle without a "
            f"viewer is raw JSON, not a demo"
        )

    # 2. dist -> bundle
    if bundle.exists():
        shutil.rmtree(bundle, ignore_errors=True)
    shutil.copytree(dist, bundle)

    # 3. swap the placeholder dataset for this subject's projection
    bundled_arch = bundle / "architecture"
    if bundled_arch.exists():
        shutil.rmtree(bundled_arch, ignore_errors=True)
    shutil.copytree(arch_dir, bundled_arch)

    # 4. the preview gate. Copied ALWAYS, not only for private previews: a gate
    # present but unconfigured denies everything (its own README: "Without it
    # the gate denies everything"), which is the safe direction. A gate absent
    # opens everything.
    if not PREVIEW_GATE_MIDDLEWARE.is_file():
        raise RuntimeError(f"preview gate middleware missing at {PREVIEW_GATE_MIDDLEWARE}")
    functions_dir = bundle / "functions"
    functions_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(PREVIEW_GATE_MIDDLEWARE, functions_dir / "_middleware.js")

    # 5. upstream license and notice (LICENSE-REVIEW.md steps 3 and 4)
    src = _src_dir(slug, corpus_dir)
    lic = _find_first(src, UPSTREAM_LICENSE_CANDIDATES)
    if lic is None:
        raise RuntimeError(
            f"no upstream license file found in {src} (looked for "
            f"{list(UPSTREAM_LICENSE_CANDIDATES)}); the bundle redistributes "
            f"upstream text and the notice must travel with it"
        )
    shutil.copy2(lic, bundle / "UPSTREAM-LICENSE.txt")
    notice = _find_first(src, UPSTREAM_NOTICE_CANDIDATES)
    if notice is not None:
        shutil.copy2(notice, bundle / notice.name)

    # 6. publication.json, if the projection carries one
    pub = arch_dir / "publication.json"
    if pub.is_file():
        shutil.copy2(pub, bundle / "publication.json")

    return bundle


def bundle_safety_errors(bundle: Path) -> list:
    """Return the reasons ``bundle`` must not be deployed. Empty means safe.

    This is the last line before an outward-facing action, so it re-checks the
    obligations against the assembled directory rather than trusting that
    assemble_bundle ran. Anything here is a hard refusal, never a warning.
    """
    errors = []
    if not bundle.is_dir():
        return [f"no bundle at {bundle}; run: bundle <slug>"]
    if not (bundle / "index.html").is_file():
        errors.append(
            f"no index.html in {bundle}: this is raw projection data, not a viewer"
        )
    if not (bundle / "functions" / "_middleware.js").is_file():
        errors.append(
            f"no functions/_middleware.js in {bundle}: the preview gate would be "
            f"absent and the deployment fully public (DISCLOSURE-POLICY.md step 3)"
        )
    if not any((bundle / n).is_file() for n in UPSTREAM_LICENSE_NAMES):
        errors.append(
            f"no upstream license in {bundle}: the bundle redistributes upstream "
            f"text (LICENSE-REVIEW.md step 3)"
        )
    return errors


# ---------------------------------------------------------------------------
# refresh: the whole chain
# ---------------------------------------------------------------------------


def _refresh_one(slug: str, *, allow_unimplemented: bool, corpus_dir: Optional[Path] = None) -> int:
    corpus = load_registry(slug)

    print(f"== refresh {slug}: fetch ==")
    try:
        _src, sha = fetch_corpus(corpus, corpus_dir)
    except (subprocess.CalledProcessError, RuntimeError, ValueError) as exc:
        print(f"error: fetch failed for '{slug}': {exc}", file=sys.stderr)
        return 1
    print(f"  resolved @ {sha}")

    print(f"== refresh {slug}: analyze ==")
    try:
        wall_s = run_analyze(corpus, corpus_dir)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError) as exc:
        print(f"error: analyze failed for '{slug}': {exc}", file=sys.stderr)
        return 1
    print(f"  {wall_s:.1f}s")

    print(f"== refresh {slug}: enhance ==")
    try:
        rc = run_enhance(corpus, corpus_dir)
    except FileNotFoundError as exc:
        print(f"error: enhance failed for '{slug}': {exc}", file=sys.stderr)
        return 1
    if rc != 0:
        print(f"  enhance for '{slug}' did not pass its own gate (exit {rc}); continuing to validate, which will report it")

    print(f"== refresh {slug}: validate ==")
    results = run_gates(corpus, corpus_dir=corpus_dir)
    for r in results:
        print(f"  [{r.state:15}] {r.name}: {r.detail}")
    ok = overall_ok(results, allow_unimplemented)
    _write_validate_record(slug, results, ok)
    if not ok:
        print(f"refresh {slug}: STOPPED at validate (gate failure)", file=sys.stderr)
        return 1

    print(f"== refresh {slug}: diff ==")
    try:
        diff = run_diff(corpus, corpus_dir)
    except FileNotFoundError as exc:
        print(f"error: diff failed for '{slug}': {exc}", file=sys.stderr)
        return 1
    print("  no baseline" if diff is None else f"  has_changes={diff['has_changes']}")

    print(f"== refresh {slug}: report ==")
    report = build_report(corpus, corpus_dir=corpus_dir)
    run_dir = _run_dir(slug)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "report.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (run_dir / "report.md").write_text(render_report_markdown(report), encoding="utf-8")

    print(f"== refresh {slug}: findings ==")
    findings = compute_findings(corpus, corpus_dir=corpus_dir)
    findings_payload = {
        "schema": "solution-explorer/demo-findings/v1", "slug": slug, "date": _today(), "findings": findings,
    }
    (run_dir / "findings.json").write_text(json.dumps(findings_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"  {len(findings)} finding(s)")

    print(f"refresh {slug}: OK")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _cmd_list(args: argparse.Namespace) -> int:
    corpora = iter_registry()
    if not corpora:
        print("no demos registered under demos/registry/")
        return 0
    for c in corpora:
        print(
            f"{c['slug']}: {c['subject']['name']} ({c['subject']['license']}, {c['subject']['governance']}) "
            f"track={c['track']} cadence={c['cadence']} -> {c['hosting']['url']}"
        )
    return 0


def _cmd_status(args: argparse.Namespace) -> int:
    corpora = iter_registry()
    if not corpora:
        print("no demos registered under demos/registry/")
        return 0
    now = datetime.now(timezone.utc)
    for c in corpora:
        last = last_successful_run(c["slug"])
        last_date = last.get("date") if last else None
        due = is_due(c, now=now)
        print(
            f"{c['slug']}: last successful refresh: {last_date or 'never'}; "
            f"due: {'yes' if due else 'no'} (cadence={c['cadence']})"
        )
    return 0


def _cmd_fetch(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    src, sha = fetch_corpus(corpus, force=args.force)
    print(f"fetched {args.slug} @ {sha} ({corpus['policy'].get('follow')}) -> {src}")
    return 0


def _cmd_analyze(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    wall_s = run_analyze(corpus)
    print(f"analyzed {args.slug} -> {_arch_dir(args.slug)} ({wall_s:.1f}s)")
    return 0


def _cmd_enhance(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    rc = run_enhance(corpus, max_partitions=args.max_partitions, dry_run=args.dry_run)
    return rc


def _cmd_validate(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    results = run_gates(corpus)
    for r in results:
        print(f"[{r.state:15}] {r.name}: {r.detail}")
    ok = overall_ok(results, args.allow_unimplemented)
    _write_validate_record(args.slug, results, ok)
    print()
    suffix = " (--allow-unimplemented)" if args.allow_unimplemented else ""
    print(f"OVERALL: {'PASS' if ok else 'FAIL'}{suffix}")
    return 0 if ok else 1


def _cmd_diff(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    diff = run_diff(corpus)
    if diff is None:
        print(f"no baseline: no previous run recorded for '{args.slug}' yet")
        return 0
    pd = _load_projection_diff()
    print(pd.render_text(diff))
    return 0


def _cmd_bundle(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    try:
        bundle = assemble_bundle(corpus, build=not args.no_build)
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"error: bundle failed for '{args.slug}': {exc}", file=sys.stderr)
        return 2
    errors = bundle_safety_errors(bundle)
    for err in errors:
        print(f"  UNSAFE: {err}", file=sys.stderr)
    if errors:
        return 2
    count = sum(1 for _ in bundle.rglob("*") if _.is_file())
    print(f"bundle assembled: {bundle} ({count} files)")
    return 0


def _cmd_deploy(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    bundle = _bundle_dir(args.slug)

    # Refuse before anything outward-facing. These are the obligations, not
    # preferences, so they are checked against the assembled directory even
    # when the caller believes it just built it.
    errors = bundle_safety_errors(bundle)
    if errors:
        print(f"error: refusing to deploy '{args.slug}':", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 2

    cf_project = corpus["hosting"]["cf_project"]
    cmd = ["wrangler", "pages", "deploy", str(bundle), "--project-name", cf_project]

    allowed = os.environ.get(DEMO_DEPLOY_ALLOW_ENV)
    if args.dry_run or not allowed:
        reason = "--dry-run passed" if args.dry_run else f"{DEMO_DEPLOY_ALLOW_ENV} is not set"
        print(f"DRY RUN ({reason}); would run:")
        print("  " + " ".join(shlex.quote(c) for c in cmd))
        return 0

    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    return result.returncode


def _cmd_report(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    report = build_report(corpus)
    run_dir = _run_dir(args.slug)
    run_dir.mkdir(parents=True, exist_ok=True)
    json_path = run_dir / "report.json"
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path = run_dir / "report.md"
    md_path.write_text(render_report_markdown(report), encoding="utf-8")
    print(f"report written: {json_path}")
    print(f"report written: {md_path}")
    return 0


def _cmd_findings(args: argparse.Namespace) -> int:
    corpus = load_registry(args.slug)
    findings = compute_findings(corpus)
    run_dir = _run_dir(args.slug)
    run_dir.mkdir(parents=True, exist_ok=True)
    out_path = run_dir / "findings.json"
    payload = {"schema": "solution-explorer/demo-findings/v1", "slug": args.slug, "date": _today(), "findings": findings}
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"{len(findings)} finding(s) written to {out_path}")
    for f in findings:
        print(f"  [{f['severity']}] {f['fingerprint']}: {f['summary']}")
    return 0


def _cmd_refresh(args: argparse.Namespace) -> int:
    if args.due:
        due_slugs = [c["slug"] for c in iter_registry() if is_due(c)]
        if not due_slugs:
            print("no demos due")
            return 0
        overall = 0
        for slug in due_slugs:
            overall = _refresh_one(slug, allow_unimplemented=args.allow_unimplemented) or overall
        return overall
    if not args.slug:
        print("error: refresh requires a slug or --due", file=sys.stderr)
        return 2
    return _refresh_one(args.slug, allow_unimplemented=args.allow_unimplemented)


def _cmd_hub(args: argparse.Namespace) -> int:
    corpora = iter_registry()
    html_doc = build_hub_html(corpora)
    HUB_DIR.mkdir(parents=True, exist_ok=True)
    out_path = HUB_DIR / "index.html"
    out_path.write_text(html_doc, encoding="utf-8")
    print(f"hub written: {out_path} ({len(corpora)} demo(s))")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="SysCorpus demo-program harness: orchestration over analyze.py, "
        "analyze.py enhance, projection-diff.py, validate-publication.py, and wrangler.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("list", help="registry contents").set_defaults(func=_cmd_list)
    sub.add_parser("status", help="last successful run per demo and what is due").set_defaults(func=_cmd_status)

    p_fetch = sub.add_parser("fetch", help="clone/fetch into the corpus cache, resolve the ref, record the SHA")
    p_fetch.add_argument("slug")
    p_fetch.add_argument("--force", action="store_true", help="re-fetch from scratch even if already up to date")
    p_fetch.set_defaults(func=_cmd_fetch)

    p_analyze = sub.add_parser("analyze", help="v2 split projection into a persistent per-demo store")
    p_analyze.add_argument("slug")
    p_analyze.set_defaults(func=_cmd_analyze)

    p_enhance = sub.add_parser("enhance", help="analyze.py enhance --update, cost-ceilinged")
    p_enhance.add_argument("slug")
    p_enhance.add_argument("--max-partitions", type=int, default=None, help="passthrough to analyze.py enhance")
    p_enhance.add_argument("--dry-run", action="store_true", help="passthrough to analyze.py enhance")
    p_enhance.set_defaults(func=_cmd_enhance)

    p_validate = sub.add_parser("validate", help="the 3.6 checklist plus the section 2 graduation gate")
    p_validate.add_argument("slug")
    p_validate.add_argument(
        "--allow-unimplemented", action="store_true",
        help="downgrade a NOT_IMPLEMENTED gate to a warning (never a FAIL or SKIP) and exit 0",
    )
    p_validate.set_defaults(func=_cmd_validate)

    p_diff = sub.add_parser("diff", help="projection diff against the previous run")
    p_diff.add_argument("slug")
    p_diff.set_defaults(func=_cmd_diff)

    p_bundle = sub.add_parser(
        "bundle",
        help="assemble the deployable bundle (viewer + projection + preview gate + upstream license)",
    )
    p_bundle.add_argument("slug")
    p_bundle.add_argument(
        "--no-build", action="store_true",
        help="reuse an existing viewer/dist instead of running the vite build",
    )
    p_bundle.set_defaults(func=_cmd_bundle)

    p_deploy = sub.add_parser("deploy", help="wrangler pages deploy (dry run unless DEMO_DEPLOY_ALLOW is set)")
    p_deploy.add_argument("slug")
    p_deploy.add_argument("--dry-run", action="store_true", help="print the command without running it")
    p_deploy.set_defaults(func=_cmd_deploy)

    p_report = sub.add_parser("report", help="write the run record, JSON and markdown")
    p_report.add_argument("slug")
    p_report.set_defaults(func=_cmd_report)

    p_findings = sub.add_parser(
        "findings", help="compute the 5.1 machine-gate findings into findings.json (never files GitHub issues)"
    )
    p_findings.add_argument("slug")
    p_findings.set_defaults(func=_cmd_findings)

    p_refresh = sub.add_parser("refresh", help="fetch -> analyze -> enhance -> validate -> diff -> report -> findings")
    p_refresh.add_argument("slug", nargs="?", default=None)
    p_refresh.add_argument("--due", action="store_true", help="refresh every demo whose cadence is up")
    p_refresh.add_argument(
        "--allow-unimplemented", action="store_true",
        help="passthrough to validate: downgrade NOT_IMPLEMENTED gates to warnings",
    )
    p_refresh.set_defaults(func=_cmd_refresh)

    sub.add_parser("hub", help="regenerate the static hub site from the registry and run records").set_defaults(func=_cmd_hub)

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except subprocess.CalledProcessError as exc:
        print(f"error: command failed ({exc})", file=sys.stderr)
        return 2
    except subprocess.TimeoutExpired as exc:
        print(f"error: command exceeded its wall-time budget ({exc})", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
